# -*- coding: utf-8 -*-
"""Banco de ejercicios UD02 · soluciones revisadas a partir de las hojas de TODO.drawio
y ejercicios nuevos (streaming, vacunas, casas rurales, casas de Juego de Tronos y
grupos del apocalipsis zombi).

Cada entrada lleva una clave `k`. Las que coinciden con un número de ud02_banco_1/2
SUSTITUYEN a ese ejercicio; las demás son nuevas. La numeración final la decide
ORDEN (ver build_banco.py y gen_svgs.py)."""
from chen_eer import *

EJS = []


def ej(**kw):
    EJS.append(kw)


# Orden final del banco (números antiguos o claves nuevas) y bloques.
ORDEN = [
    # Bloque 1 · Fundamentos
    1, "streaming", 3, 2, 4,
    # Bloque 2 · Intermedio
    5, 6, "vacunas", 7, 8, "rurales", 9, 10, 11, 12,
    # Bloque 3 · Integración
    13, 14, 15, 16, 17, 18, "got", 19,
    # Bloque 4 · EER avanzado
    20, 21, 22, 23, 24, "zombis", 25,
]
TAM_BLOQUES = [5, 10, 8, 7]


# ------------------------------------------------------------------ 4 · Parentesco (revisado)
ej(k=4, titulo="Parentesco y filiación", nivel=1, dur="1 sesión",
   ra="RA6: d, h", entrega="Diagrama EER + análisis del enunciado",
   objetivo="Modelar una relación **reflexiva** con roles, detectar una cardinalidad mínima imposible y fijar un máximo concreto (2).",
   contexto="Un registro genealógico quiere guardar quién es progenitor de quién.",
   enun=["Se desea diseñar una base de datos que registre las relaciones de parentesco entre **personas**. De cada persona se conocen el DNI, el nombre, la dirección y el teléfono.",
         "Una persona puede ser progenitora (padre o madre) de varios hijos o hijas, o de ninguno. Toda persona registrada en el sistema debe tener registrada obligatoriamente su filiación directa con su progenitor o progenitora."],
   tareas=["Dibuja el diagrama EER con una **relación reflexiva** y los **roles** (progenitor, hijo).",
           "Escribe las cardinalidades (mín, máx) de cada rol. ¿Cuántos progenitores puede tener una persona como máximo?",
           "Razona si el mínimo que pide el enunciado («obligatoriamente») se puede mantener en una base de datos real y propón uno viable.",
           "Colorea el rombo según la notación del módulo y explica por qué queda entero en negro."],
   comp=["Solo hay una entidad y la relación sale y vuelve a ella.",
         "Los dos extremos de la relación tienen **rol**.",
         "El máximo del rol *progenitor* es **2** (padre y madre), no 1 ni N.",
         "Has detectado el problema de las personas sin ascendientes registrados y el mínimo del rol *progenitor* es 0."],
   err=["Crear dos entidades `PADRE` e `HIJO`. Ambos son `PERSONA` y una persona puede ser a la vez padre e hijo.",
        "Poner (1,1) en el rol de progenitor: solo permitiría registrar a uno de los dos progenitores y, además, obligaría a que todas las personas tuvieran uno registrado.",
        "Dibujar el rombo mitad blanco y mitad negro: los dos máximos (2 y N) son mayores que 1, así que las dos mitades van en negro."],
   pista=("Pista: ¿quién es el primer antepasado?",
          "Si todas las personas deben tener progenitor registrado y la base de datos es finita, la cadena de ascendientes tendría que cerrarse en un ciclo. Esto es imposible. El mínimo del rol *progenitor* tiene que ser 0."),
   amp="Se quiere distinguir la filiación **biológica** de la **adoptiva** y registrar la fecha de adopción. ¿Dónde colocas esos atributos? ¿Sigue siendo 2 el máximo del rol *progenitor*?",
   dec=["*Tiene hijos* es una relación reflexiva **N:M**: una persona tiene hasta 2 progenitores registrados y puede tener muchos hijos. Por eso el rombo es negro entero.",
        "El enunciado pide que la filiación sea obligatoria (mínimo 1), pero eso es insostenible: se corrige a **(0,2)** y se documenta como restricción de negocio (RA6.h).",
        "El máximo 2 es una cardinalidad concreta: se escribe tal cual en el diagrama. Al pasar al modelo relacional (UD03) no se puede controlar solo con claves; necesitará un `CHECK` o un disparador.",
        "Los roles distinguen los dos extremos de la misma entidad."],
   sup=["Las personas fundadoras del árbol no tienen progenitor registrado: mínimo 0.",
        "Una persona tiene como máximo dos progenitores registrados (padre y madre).",
        "Una persona no puede ser progenitora de sí misma ni de sus ascendientes (restricción que el diagrama no recoge)."],
   model=Model("Parentesco y filiación",
               "PERSONA tiene hijos PERSONA: relación reflexiva N:M con los roles progenitor (0,2) e hijo (0,N).",
               [E("PERSONA", [K("dni"), A("nombre"), A("dirección"), A("teléfono")])],
               [R("tiene hijos", [("PERSONA", "(0,2)", "progenitor"), ("PERSONA", "(0,N)", "hijo")])]))

# ------------------------------------------------------------------ 5 · Instituto (revisado)
ej(k=5, titulo="Instituto: módulos, matrículas, delegados y casilleros", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones textuales",
   objetivo="Distinguir una relación 1:1 opcional, una N:M reflexiva y una 1:N reflexiva en un mismo modelo.",
   contexto="Un instituto de Educación Secundaria y Formación Profesional diseña su base de datos de docencia.",
   enun=["De los **profesores** se guarda el DNI, el nombre, la dirección y el teléfono. Los profesores imparten **módulos**, cada uno con un código y un nombre. Un profesor puede impartir varios módulos, pero cada módulo lo imparte un único profesor.",
         "Algunos módulos tienen como **prerrequisito** haber cursado otros. Un módulo puede exigir varios módulos previos y, a su vez, ser requisito de otros.",
         "De cada **alumno** se almacena el número de expediente, el nombre, los apellidos, la fecha de nacimiento y el curso. Un alumno se matricula en uno o varios módulos y se registra la fecha de matriculación.",
         "Cada curso cuenta con un grupo de alumnos. Dentro de cada grupo se elige a uno de ellos como **delegado**, que representa a sus compañeros.",
         "Los alumnos que lo soliciten pueden disponer de un **casillero** (número y tamaño en metros). Un casillero pertenece a un único alumno y un alumno tiene como máximo un casillero."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Modela al delegado **sin crear una entidad nueva**. ¿Qué tipo de relación necesitas? Escribe sus roles.",
           "Calcula las cardinalidades de la relación con el casillero y razona por qué el mínimo es 0 en los dos lados.",
           "Escribe al menos **dos restricciones** que el diagrama no puede expresar."],
   comp=["*Es requisito de* es una N:M **reflexiva** sobre `MÓDULO` con dos roles.",
         "*Es delegado de* es una 1:N **reflexiva** sobre `ALUMNO`.",
         "La relación alumno–casillero es 1:1 con (0,1) en los dos lados: el rombo es blanco entero.",
         "`fecha_matrícula` está en la relación *se matricula*, no en `ALUMNO`."],
   err=["Usar un atributo `es_delegado` en `ALUMNO`: no dice a quién representa ni garantiza un único delegado por grupo.",
        "Dibujar *es requisito de* como 1:N. Un módulo puede tener varios previos y ser previo de varios.",
        "Poner la fecha de matrícula en `ALUMNO`: un alumno se matricula de varios módulos, quizá en fechas distintas."],
   pista=("Pista: el delegado también es un alumno",
          "Cuando una entidad se relaciona consigo misma se usa una **relación reflexiva**. Un alumno (rol *delegado*) representa a muchos alumnos (rol *representado*) y cada alumno tiene, como mucho, un delegado."),
   amp="El centro decide guardar los **grupos** como entidad (código, curso, aula). Rediseña la parte del delegado: ¿qué relaciones aparecen entre `ALUMNO` y `GRUPO`? ¿Por qué no pueden fusionarse en una sola?",
   dec=["*Imparte* es 1:N; *se matricula* es N:M con atributo; *es requisito de* es N:M reflexiva.",
        "*Es delegado de* es una reflexiva 1:N: un alumno delegado representa a (0,N) compañeros y cada alumno tiene (0,1) delegado (0 mientras no se haya elegido).",
        "*Tiene* (casillero) es 1:1 con mínimos 0: no todos los alumnos piden casillero y puede haber casilleros libres. Este caso, con (0,1) en los dos lados, se transforma en la UD03 con una tabla propia.",
        "El curso es un atributo de `ALUMNO`. Si el grupo tuviera más datos, pasaría a ser una entidad (ver ampliación)."],
   sup=["Todo módulo tiene profesor asignado: (1,1).",
        "Un alumno matriculado lo está al menos de un módulo: (1,N).",
        "El delegado y sus representados son del mismo curso (restricción textual).",
        "Un módulo no puede ser prerrequisito de sí mismo ni formar ciclos (restricción textual)."],
   model=Model("Instituto: módulos, matrículas, delegados y casilleros",
               "PROFESOR imparte MÓDULO (1:N); MÓDULO es requisito de MÓDULO (N:M reflexiva); ALUMNO se matricula en MÓDULO (N:M con fecha); ALUMNO es delegado de ALUMNO (1:N reflexiva); ALUMNO tiene CASILLERO (1:1).",
               [E("PROFESOR", [K("dni"), A("nombre"), A("dirección"), A("teléfono")]),
                E("MÓDULO", [K("código"), A("nombre")]),
                E("ALUMNO", [K("nº_expediente"), A("nombre"), A("apellidos"), A("fecha_nacimiento"), A("curso")]),
                E("CASILLERO", [K("nº_casillero"), A("tamaño_m")])],
               [R("imparte", [("PROFESOR", "(1,1)", None), ("MÓDULO", "(1,N)", None)]),
                R("es requisito de", [("MÓDULO", "(0,N)", "previo"), ("MÓDULO", "(0,N)", "posterior")]),
                R("se matricula", [("ALUMNO", "(0,N)", None), ("MÓDULO", "(1,N)", None)], [A("fecha_matrícula")]),
                R("es delegado de", [("ALUMNO", "(0,1)", "delegado"), ("ALUMNO", "(0,N)", "representado")]),
                R("tiene", [("ALUMNO", "(0,1)", None), ("CASILLERO", "(0,1)", None)])]))

# ------------------------------------------------------------------ streaming (nuevo)
ej(k="streaming", titulo="Películas en streaming", nivel=1, dur="1 sesión",
   ra="RA6: a, d, e", entrega="Diagrama EER + supuestos",
   objetivo="Convertir en entidades los datos por los que se busca (actor, género) y descubrir que un hecho («haber visto») es una relación, no un atributo booleano.",
   contexto="Una plataforma de cine bajo demanda quiere recomendar películas y avisar al cliente de lo que ya ha visto.",
   enun=["Se desea crear una base de datos para una plataforma de películas en *streaming*.",
         "A los **clientes** se les piden sus datos personales (NIF, nombre, apellidos, correo electrónico y dirección) y el sistema mantiene el **saldo** disponible de su cuenta.",
         "Los clientes pueden buscar **películas** por **género**, por **actores** y por título. De cada película se guarda un código, el título, el año de estreno y la duración en minutos. De los actores se conoce un código, el nombre completo y la nacionalidad. Cada película pertenece a un género (comedia, drama, terror…).",
         "La plataforma debe avisar al cliente si una película **ya la ha visto**. Para ello registra qué películas ha visto cada cliente, la fecha y la valoración (de 1 a 5) que le ha dado."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Explica por qué `ACTOR` y `GÉNERO` son entidades y no atributos de `PELÍCULA`.",
           "¿Hace falta un atributo `vista (sí/no)`? Razona la respuesta.",
           "Anota los supuestos."],
   comp=["Hay cuatro entidades: `CLIENTE`, `PELÍCULA`, `ACTOR` y `GÉNERO`.",
         "*Ve* es N:M y lleva `fecha` y `valoración`.",
         "*Actúa en* es N:M y *pertenece a* es 1:N.",
         "No existe ningún atributo booleano «vista»."],
   err=["Añadir `vista (sí/no)` a la relación: si existe la pareja cliente–película, ya la ha visto; si no existe, no. El booleano es redundante.",
        "Guardar `actor` y `género` como atributos de `PELÍCULA`: una película tiene varios actores y buscar por ellos obligaría a recorrer texto libre.",
        "Poner el `saldo` en una entidad aparte: es un dato de cada cliente."],
   amp="Una película puede pertenecer a **varios géneros** (comedia romántica, terror psicológico…). ¿Qué cambia en la relación *pertenece a*? ¿Y en el color del rombo?",
   dec=["*Ve* es **N:M** con `fecha` y `valoración`: la existencia de la pareja (cliente, película) ya indica que la ha visto. Si se quiere guardar cada visionado, la fecha pasa a formar parte de la identificación (subrayado discontinuo).",
        "*Actúa en* es N:M: un actor participa en muchas películas y una película tiene muchos actores.",
        "*Pertenece a* es 1:N: cada película tiene un género y un género agrupa muchas películas. El rombo tiene la mitad blanca junto a `GÉNERO` (máximo 1) y la negra junto a `PELÍCULA` (máximo N)."],
   sup=["Un cliente puede no haber visto ninguna película todavía: (0,N).",
        "Toda película tiene al menos un actor registrado: (1,N).",
        "Se guarda cada visionado, de modo que un cliente puede ver la misma película en fechas distintas.",
        "La valoración es un entero entre 1 y 5 (restricción de dominio)."],
   model=Model("Películas en streaming",
               "CLIENTE ve PELÍCULA (N:M con fecha y valoración). ACTOR actúa en PELÍCULA (N:M). PELÍCULA pertenece a GÉNERO (N:1).",
               [E("CLIENTE", [K("nif"), A("nombre"), A("apellidos"), A("email"), A("dirección"), A("saldo")]),
                E("PELÍCULA", [K("cód_película"), A("título"), A("año_estreno"), A("duración_min")]),
                E("ACTOR", [K("cód_actor"), A("nombre"), A("nacionalidad")]),
                E("GÉNERO", [K("cód_género"), A("nombre")])],
               [R("ve", [("CLIENTE", "(0,N)", None), ("PELÍCULA", "(0,N)", None)], [KP("fecha"), A("valoración")]),
                R("actúa en", [("ACTOR", "(1,N)", None), ("PELÍCULA", "(0,N)", None)]),
                R("pertenece a", [("PELÍCULA", "(0,N)", None), ("GÉNERO", "(1,1)", None)])]))

# ------------------------------------------------------------------ vacunas (nuevo)
ej(k="vacunas", titulo="Clínica veterinaria: calendario de vacunación", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + supuestos",
   objetivo="Separar los datos que se **calculan** (edad, próxima vacuna) de los que se guardan y evitar relaciones redundantes.",
   contexto="Una clínica veterinaria quiere avisar a los dueños de las vacunas pendientes de sus animales.",
   enun=["Queremos crear una base de datos para una clínica veterinaria con el fin de controlar el calendario de vacunación de los animales y avisar al dueño cuándo debe acudir a la clínica.",
         "De cada **cliente** (dueño) se guardan el DNI, el nombre, los apellidos, la dirección, el teléfono y el correo electrónico. Un cliente puede tener varios animales.",
         "De cada **animal** se conoce un código, el nombre, el tipo (perro, gato…), la raza y la fecha de nacimiento; también se quiere mostrar su edad.",
         "De cada **vacuna** se guarda un código, el nombre y cada cuántos días hay que repetirla. Cuando se administra una vacuna a un animal se registra la fecha; la próxima fecha de vacunación se calcula a partir de la última administración y del tipo de vacuna.",
         "La clínica envía **notificaciones**: de cada una se guarda un número, la fecha de envío, la vacuna pendiente y la fecha prevista de administración.",
         "Se registran también las **visitas** de cada animal: fecha, tipo de visita (vacunación, consulta…) y notas."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Marca los atributos **derivados** y explica de qué datos se obtienen.",
           "¿Debe relacionarse `NOTIFICACIÓN` directamente con `CLIENTE`? Razona la respuesta.",
           "Decide si `VISITA` es una entidad débil y escribe su identificador completo."],
   comp=["`edad` y `próxima_fecha` son derivados (óvalo discontinuo).",
         "*Se vacuna* es N:M entre `ANIMAL` y `VACUNA` y la fecha permite repetir la misma vacuna.",
         "`NOTIFICACIÓN` se relaciona con `ANIMAL` y con `VACUNA`, no con `CLIENTE`.",
         "`VISITA` es débil de `ANIMAL` (etiqueta ID)."],
   err=["Guardar la edad: cambia cada día. Se calcula a partir de la fecha de nacimiento.",
        "Guardar «tipo de vacuna pendiente» como texto en la notificación: debe ser una relación con `VACUNA`.",
        "Relacionar la notificación con el cliente **y** con el animal: el dueño se obtiene a partir del animal, y las dos relaciones podrían contradecirse."],
   amp="Algunas vacunas se ponen **durante una visita**. ¿Cómo relacionarías la administración de la vacuna con la visita? ¿Qué problema aparece si una visita incluye dos vacunas?",
   dec=["*Es dueño de* es 1:N: cada animal tiene un único dueño registrado.",
        "*Se vacuna* es N:M con `fecha` como discriminador (una vacuna se repite cada cierto tiempo) y `próxima_fecha` como atributo derivado.",
        "`NOTIFICACIÓN` es una entidad con identificador propio relacionada 1:N con `ANIMAL` y con `VACUNA`; el cliente se deduce del animal.",
        "`VISITA` es débil: se identifica por (código del animal, fecha)."],
   sup=["Todo animal tiene dueño: (1,1).",
        "Un animal no recibe dos veces la misma vacuna el mismo día.",
        "Un animal no tiene dos visitas en la misma fecha.",
        "La próxima fecha = última administración + periodicidad de la vacuna (regla de cálculo)."],
   model=Model("Clínica veterinaria: calendario de vacunación",
               "CLIENTE es dueño de ANIMAL (1:N). ANIMAL se vacuna con VACUNA (N:M con fecha). NOTIFICACIÓN avisa de VACUNA y se envía por ANIMAL. ANIMAL tiene VISITA (débil).",
               [E("CLIENTE", [K("dni"), A("nombre"), A("apellidos"), A("dirección"), A("teléfono"), A("email")]),
                E("ANIMAL", [K("cód_animal"), A("nombre"), A("tipo"), A("raza"), A("fecha_nacimiento"), D("edad")]),
                E("VACUNA", [K("cód_vacuna"), A("nombre"), A("periodicidad_días")]),
                E("NOTIFICACIÓN", [K("nº_notificación"), A("fecha_envío"), A("fecha_prevista")]),
                E("VISITA", [KP("fecha"), A("tipo"), A("notas")], weak=True)],
               [R("es dueño de", [("CLIENTE", "(1,1)", None), ("ANIMAL", "(1,N)", None)]),
                R("se vacuna", [("ANIMAL", "(0,N)", None), ("VACUNA", "(0,N)", None)], [KP("fecha"), D("próxima_fecha")]),
                R("avisa de", [("NOTIFICACIÓN", "(0,N)", None), ("VACUNA", "(1,1)", None)]),
                R("se envía por", [("ANIMAL", "(1,1)", None), ("NOTIFICACIÓN", "(0,N)", None)]),
                R("pasa", [("ANIMAL", "(1,1)", None), ("VISITA", "(0,N)", None)], ident=True)]))

# ------------------------------------------------------------------ casas rurales (nuevo)
ej(k="rurales", titulo="Casas rurales: provincias, ciudades y habitaciones", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + identificadores completos",
   objetivo="Encadenar dos entidades débiles por identificación y modelar una estancia repetible con fechas.",
   contexto="Una central de reservas de turismo rural quiere gestionar su oferta de alojamientos.",
   enun=["De cada **provincia** se guarda el nombre, el área y la población. En cada provincia hay **ciudades**, de las que se conoce el nombre y el número de habitantes. El nombre de una ciudad **solo es único dentro de su provincia** (hay varias ciudades llamadas «Villanueva»).",
         "Las **casas rurales** tienen un nombre único, una localización y si ofrecen desayuno. Cada casa está en una ciudad y en una ciudad puede haber varias casas.",
         "Cada casa tiene varias **habitaciones**, numeradas dentro de la casa (1, 2, 3…), con una descripción y un precio por noche.",
         "Los **clientes** (DNI, nombre, dirección y teléfono) se alojan en habitaciones. De cada estancia se guarda la fecha de entrada y la de salida. Un cliente puede alojarse varias veces en la misma habitación."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Escribe el **identificador completo** de `CIUDAD` y de `HABITACIÓN`.",
           "¿Qué atributo permite que un cliente repita la misma habitación? Márcalo en el diagrama.",
           "Anota los supuestos."],
   comp=["`CIUDAD` es débil de `PROVINCIA` y `HABITACIÓN` es débil de `CASA_RURAL` (etiqueta ID).",
         "*Está en* (casa–ciudad) es 1:N y **no** es identificadora: el nombre de la casa ya es único.",
         "*Se aloja* es N:M y `fecha_entrada` forma parte de la identificación.",
         "`desayuno` es un atributo de `CASA_RURAL`."],
   err=["Dar a `CIUDAD` el nombre como clave: dos provincias pueden tener una ciudad con el mismo nombre.",
        "Relacionar al cliente con la casa en lugar de con la habitación: se pierde qué habitación ocupó.",
        "Identificar la estancia solo con (cliente, habitación): impide alojarse dos veces en la misma habitación."],
   amp="Variante: además de alquilar, se quiere saber qué **personas viven** en cada casa (cada persona vive en una sola) y qué personas **son propietarias** (una casa puede tener varios propietarios y se guarda la fecha de compra). Las casas tienen ahora un identificador propio y **no pueden existir sin su ciudad** (dependencia en existencia, etiqueta E). Dibuja el diagrama de esta variante.",
   dec=["`CIUDAD` depende de `PROVINCIA` en identificación: su identificador es (nombre de la provincia, nombre de la ciudad).",
        "`HABITACIÓN` depende de `CASA_RURAL`: su identificador es (nombre de la casa, número).",
        "*Se aloja* es N:M con `fecha_entrada` (discriminador) y `fecha_salida`.",
        "El rombo de *está en* tiene la mitad blanca junto a `CIUDAD` (máximo 1) y la negra junto a `CASA_RURAL`."],
   sup=["Toda casa está en una ciudad: (1,1).",
        "Una ciudad puede no tener casas rurales: (0,N).",
        "Una casa tiene al menos una habitación: (1,N).",
        "La fecha de salida es posterior a la de entrada (restricción textual)."],
   model=Model("Casas rurales: provincias, ciudades y habitaciones",
               "PROVINCIA tiene CIUDAD (débil). CASA_RURAL está en CIUDAD (N:1). CASA_RURAL tiene HABITACIÓN (débil). CLIENTE se aloja en HABITACIÓN (N:M con fechas).",
               [E("PROVINCIA", [K("nombre"), A("área"), A("población")]),
                E("CIUDAD", [KP("nombre"), A("habitantes")], weak=True),
                E("CASA_RURAL", [K("nombre"), A("localización"), A("desayuno")]),
                E("HABITACIÓN", [KP("número"), A("descripción"), A("precio")], weak=True),
                E("CLIENTE", [K("dni"), A("nombre"), A("dirección"), A("teléfono")])],
               [R("está situada", [("PROVINCIA", "(1,1)", None), ("CIUDAD", "(1,N)", None)], ident=True),
                R("está en", [("CASA_RURAL", "(0,N)", None), ("CIUDAD", "(1,1)", None)]),
                R("dispone de", [("CASA_RURAL", "(1,1)", None), ("HABITACIÓN", "(1,N)", None)], ident=True),
                R("se aloja", [("CLIENTE", "(0,N)", None), ("HABITACIÓN", "(0,N)", None)], [KP("fecha_entrada"), A("fecha_salida")])]))

# ------------------------------------------------------------------ Juego de Tronos (nuevo)
ej(k="got", titulo="Casas de Juego de Tronos: castillos, arquitectos y mecenazgos", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + justificación de la agregación",
   objetivo="Usar una **agregación** para relacionar una entidad con una relación N:M, junto con una entidad débil y una reflexiva.",
   contexto="George R. R. Martin quiere documentar los castillos de las grandes casas de Poniente.",
   enun=["De cada **casa** (Stark, Tully, Lannister…) se guarda un número de orden según el año de fundación, el nombre (que es único), el año de fundación, la localización, la dirección (valle, montaña y arroyo) y los metros cuadrados.",
         "Cada casa tiene una serie de **castillos**. De cada castillo se guarda un código **establecido por cada casa**, el nombre, las medidas, la fecha y el estilo de construcción (gótico, románico…) y una descripción de la técnica utilizada.",
         "Cada castillo lo crea un **arquitecto**, del que se conoce el nombre, la nacionalidad, la fecha de nacimiento y la de fallecimiento. Un arquitecto puede tener como **maestro** a otro arquitecto de la base de datos; a su vez, un maestro puede serlo de varios o de ninguno. Los arquitectos pueden pertenecer o no a una **escuela** (nombre, país, fecha de aparición y estilo).",
         "Los arquitectos pueden tener uno o varios **mecenas** (nombre, que puede repetirse, país y ciudad de nacimiento, fecha de nacimiento y de fallecimiento), y un mecenas puede serlo de varios arquitectos. De cada **mecenazgo** se quiere saber la fecha de inicio, la de fin y la población donde tuvo lugar, y **qué castillos resultaron** de cada mecenazgo."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Escribe el identificador completo de `CASTILLO`.",
           "Los castillos se relacionan con el **mecenazgo**, que es una relación. Compara dos soluciones: una ternaria (arquitecto, mecenas, castillo) y una **agregación**. ¿Cuál representa mejor el enunciado?",
           "¿Qué identificador das a `MECENAS` si su nombre puede repetirse?"],
   comp=["`CASTILLO` es débil de `CASA` (etiqueta ID).",
         "*Es maestro de* es una reflexiva 1:N sobre `ARQUITECTO`.",
         "*Mecenazgo* es N:M y queda dentro de un recuadro de **agregación**.",
         "La relación *resulta de* une `CASTILLO` con la agregación, no con `ARQUITECTO` ni con `MECENAS` por separado.",
         "`MECENAS` tiene un código artificial como identificador."],
   err=["Usar una ternaria: obligaría a que todo mecenazgo tuviera un castillo, y el enunciado admite mecenazgos sin castillos.",
        "Relacionar `CASTILLO` solo con `MECENAS`: se pierde qué arquitecto trabajó para él en ese mecenazgo.",
        "Usar el nombre del mecenas como clave: se repite."],
   pista=("Pista: relacionar algo con una relación",
          "En el modelo E/R una relación solo une entidades. Cuando necesitas relacionar una entidad con el **hecho** de que dos entidades estén relacionadas (el mecenazgo), encierra esa relación en una **agregación** y trátala como si fuera una entidad."),
   amp="Un castillo puede ser fruto de **varios mecenazgos** (por ejemplo, empezado con un mecenas y terminado con otro). ¿Cómo cambia la cardinalidad de *resulta de*? ¿Y el color del rombo?",
   dec=["`CASTILLO` depende de `CASA` en identificación: (nº de orden de la casa, código del castillo).",
        "El nombre de la casa es **clave alternativa** (subrayado de puntos): es único, pero se identifica por el número de orden.",
        "*Mecenazgo* es N:M con `fecha_inicio` como discriminador, `fecha_fin` y `población`. Se agrega para poder relacionarlo con `CASTILLO`.",
        "*Resulta de* es 1:N entre la agregación y `CASTILLO`: cada castillo procede como mucho de un mecenazgo; un mecenazgo puede producir varios castillos o ninguno.",
        "La solución con ternaria (la del primer borrador) es válida solo si todo mecenazgo produce castillos."],
   sup=["Todo castillo tiene un arquitecto creador: (1,1).",
        "Un arquitecto puede no pertenecer a ninguna escuela: (0,1).",
        "Un arquitecto no puede ser maestro de sí mismo (restricción textual).",
        "El arquitecto que construye el castillo es el del mecenazgo del que resulta (restricción textual)."],
   model=Model("Casas de Juego de Tronos: castillos, arquitectos y mecenazgos",
               "CASA tiene CASTILLO (débil). ARQUITECTO construye CASTILLO, es maestro de ARQUITECTO y pertenece a ESCUELA. ARQUITECTO y MECENAS forman el MECENAZGO (N:M), agregado y relacionado con CASTILLO.",
               [E("CASA", [K("nº_orden"), AK("nombre"), A("año_fundación"), A("localización"), C("dirección", "valle", "montaña", "arroyo"), A("m2")]),
                E("CASTILLO", [KP("código"), A("nombre"), A("medidas"), A("fecha"), A("estilo"), A("técnica")], weak=True),
                E("ARQUITECTO", [K("cód_arquitecto"), A("nombre"), A("nacionalidad"), A("fecha_nac"), A("fecha_fall")]),
                E("ESCUELA", [K("nombre"), A("país"), A("fecha_aparición"), A("estilo")]),
                E("MECENAS", [K("cód_mecenas"), A("nombre"), A("país"), A("ciudad_nac"), A("fecha_nac"), A("fecha_fall")])],
               [R("posee", [("CASA", "(1,1)", None), ("CASTILLO", "(0,N)", None)], ident=True),
                R("construye", [("ARQUITECTO", "(1,1)", None), ("CASTILLO", "(0,N)", None)]),
                R("es maestro de", [("ARQUITECTO", "(0,1)", "maestro"), ("ARQUITECTO", "(0,N)", "discípulo")]),
                R("pertenece", [("ARQUITECTO", "(0,N)", None), ("ESCUELA", "(0,1)", None)]),
                R("mecenazgo", [("ARQUITECTO", "(1,N)", None), ("MECENAS", "(0,N)", None)], [KP("fecha_inicio"), A("fecha_fin"), A("población")]),
                R("resulta de", [("MECENAZGO", "(0,1)", None), ("CASTILLO", "(0,N)", None)])],
               aggs=[AGG("MECENAZGO", ["ARQUITECTO", "mecenazgo", "MECENAS"])],
               pos={"CASA": (-0.3, -0.2), "posee": (2.2, 0), "CASTILLO": (4.4, 0), "construye": (4.4, 1.9),
                    "ARQUITECTO": (4.4, 3.8), "es maestro de": (6.6, 3.8), "pertenece": (4.4, 5.7), "ESCUELA": (4.4, 7.4),
                    "mecenazgo": (2.2, 3.8), "MECENAS": (0, 3.8), "resulta de": (1.1, 1.6)}))

# ------------------------------------------------------------------ 19 · Quidditch (sustituido por el campeonato)
ej(k=19, titulo="Campeonato de Quidditch", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + clasificación de la jerarquía + restricciones",
   objetivo="Integrar una **generalización** con atributos propios, dos entidades débiles, una reflexiva, un atributo multivaluado y una cardinalidad máxima concreta (2).",
   contexto="Se va a celebrar un campeonato de *quidditch* entre selecciones de distintos países.",
   enun=["En el campeonato participan **jugadores** y **árbitros**. De todos ellos se quiere conocer el número de mago, el nombre, la dirección y los **campeonatos** en los que han participado. De los jugadores se guarda además el nivel de juego (numérico) y de los árbitros, la categoría (nacional o internacional). Ningún árbitro puede participar como jugador.",
         "Los **países** envían al campeonato **equipos** y árbitros, aunque no todos los países envían selección. Todo equipo y todo árbitro es enviado por un único país. Un país puede estar **representado** por otro país. Cada país se identifica por un número correlativo según su orden alfabético y se guarda su nombre y el número de clubes de quidditch que existen en él. Cada equipo tiene un nombre y está formado por varios jugadores.",
         "Cada **juego** (partida) se identifica por un número correlativo (Cod-Q). Lo juegan **dos equipos** y lo arbitra un árbitro. Todo equipo participa al menos en un juego. Un árbitro no puede arbitrar a equipos enviados por su mismo país.",
         "Los participantes se alojan en los **castillos** donde se desarrollan las partidas y se quiere saber en qué castillo y en qué fechas se ha alojado cada uno; pueden alojarse varias veces, en el mismo o en distinto castillo. De cada castillo se guarda el nombre, la dirección y el teléfono.",
         "El campeonato se desarrolla a lo largo de una serie de **jornadas** (fecha). Cada juego tiene lugar en una jornada, aunque puede haber jornadas de descanso.",
         "Cada juego se celebra en un **estadio** de uno de los castillos (los estadios se numeran dentro de cada castillo) y se guarda el número de entradas vendidas. De cada estadio se conoce la capacidad y los **medios** de que dispone para la retransmisión (radio, televisión, vídeo…).",
         "De cada juego se registran todos los **movimientos**, identificados por un número de orden dentro del juego; de cada uno se guarda la jugada y un breve comentario de un experto."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica la generalización de `PARTICIPANTE` (total/parcial, disjunta/solapada) y justifícalo con frases del enunciado.",
           "¿Qué cardinalidad tiene `EQUIPO` en la relación *juega*? ¿Qué color tiene esa mitad del rombo?",
           "Escribe las restricciones que el diagrama no puede expresar."],
   comp=["`PARTICIPANTE` se generaliza en `JUGADOR` y `ÁRBITRO` con **T,D**.",
         "*Juega* tiene (2,2) junto a `EQUIPO`.",
         "`ESTADIO` es débil de `CASTILLO` y `MOVIMIENTO` es débil de `JUEGO` (etiqueta ID).",
         "`campeonato` (de los participantes) y `medios` (de los estadios) son multivaluados.",
         "*Se aloja* es N:M y la fecha de entrada forma parte de la identificación."],
   err=["Repetir número de mago, nombre y dirección en `JUGADOR` y en `ÁRBITRO`: van en la superclase.",
        "Guardar las entradas vendidas en `ESTADIO`: dependen de cada juego.",
        "Hacer de la fecha un atributo de `JUEGO` y olvidar que el enunciado pide jornadas sin juegos (de descanso).",
        "Relacionar `JUGADOR` directamente con `PAÍS`: el país se obtiene a través del equipo."],
   pista=("Pista: dos equipos por juego",
          "Cuando el número de participantes es fijo se escribe el número en la cardinalidad: (2,2) junto a `EQUIPO`. La mitad del rombo que mira a `EQUIPO` es negra, porque el máximo (2) es mayor que 1."),
   amp="Se quiere distinguir el equipo **local** del **visitante**. Propón dos alternativas (dos relaciones 1:N o una relación con un atributo `papel`) y explica qué restricción textual necesita cada una.",
   dec=["Generalización **total y disjunta**: todo participante es jugador o árbitro y «ningún árbitro puede participar como jugador».",
        "*Juega* es N:M con máximo 2 en el lado del equipo; *arbitra*, *tiene lugar* y *se celebra en* son 1:N.",
        "*Se celebra en* lleva `entradas_vendidas`, que depende del juego y del estadio.",
        "*Representa a* es una reflexiva 1:N sobre `PAÍS`.",
        "`JORNADA` es entidad porque existen jornadas sin juegos."],
   sup=["Un equipo tiene al menos un jugador: (1,N).",
        "Un país puede no enviar equipo ni árbitros: (0,N).",
        "Un árbitro no arbitra juegos de equipos de su país (restricción textual).",
        "Los dos equipos de un juego son distintos (restricción textual).",
        "Un participante no está alojado en dos castillos a la vez (restricción textual)."],
   model=Model("Campeonato de Quidditch",
               "PARTICIPANTE se generaliza (T,D) en JUGADOR y ÁRBITRO. PAÍS envía EQUIPO y ÁRBITRO y representa a PAÍS. EQUIPO está formado por JUGADOR y juega JUEGO (2,2). ÁRBITRO arbitra JUEGO. JUEGO tiene lugar en JORNADA y se celebra en ESTADIO (débil de CASTILLO). JUEGO registra MOVIMIENTO (débil). PARTICIPANTE se aloja en CASTILLO.",
               [E("PARTICIPANTE", [K("nº_mago"), A("nombre"), A("dirección"), MV("campeonato")]),
                E("JUGADOR", [A("nivel")]),
                E("ÁRBITRO", [A("categoría")]),
                E("PAÍS", [K("nº_país"), A("nombre"), A("nº_clubes")]),
                E("EQUIPO", [K("nombre")]),
                E("JUEGO", [K("cod_q")]),
                E("JORNADA", [K("fecha")]),
                E("CASTILLO", [K("nombre"), A("dirección"), A("teléfono")]),
                E("ESTADIO", [KP("nº_estadio"), A("capacidad"), MV("medios")], weak=True),
                E("MOVIMIENTO", [KP("nº_orden"), A("jugada"), A("comentario")], weak=True)],
               [R("envía", [("PAÍS", "(1,1)", None), ("EQUIPO", "(0,N)", None)], rid="envía_eq"),
                R("envía", [("PAÍS", "(1,1)", None), ("ÁRBITRO", "(0,N)", None)], rid="envía_arb"),
                R("representa a", [("PAÍS", "(0,1)", "representante"), ("PAÍS", "(0,N)", "representado")]),
                R("forma", [("EQUIPO", "(1,1)", None), ("JUGADOR", "(1,N)", None)]),
                R("juega", [("EQUIPO", "(2,2)", None), ("JUEGO", "(1,N)", None)]),
                R("arbitra", [("ÁRBITRO", "(1,1)", None), ("JUEGO", "(0,N)", None)]),
                R("tiene lugar", [("JUEGO", "(0,N)", None), ("JORNADA", "(1,1)", None)]),
                R("se celebra en", [("JUEGO", "(0,N)", None), ("ESTADIO", "(1,1)", None)], [A("entradas_vendidas")]),
                R("dispone de", [("CASTILLO", "(1,1)", None), ("ESTADIO", "(1,N)", None)], ident=True),
                R("registra", [("JUEGO", "(1,1)", None), ("MOVIMIENTO", "(0,N)", None)], ident=True),
                R("se aloja", [("PARTICIPANTE", "(0,N)", None), ("CASTILLO", "(0,N)", None)], [KP("fecha_entrada"), A("fecha_salida")])],
               [ISA("PARTICIPANTE", ["JUGADOR", "ÁRBITRO"], "d", True)]))

# ------------------------------------------------------------------ zombis (nuevo)
ej(k="zombis", titulo="Grupos de supervivientes del apocalipsis zombi", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + clasificación de la jerarquía + restricciones",
   objetivo="Combinar una especialización con atributos propios, un atributo derivado, una entidad débil y una reflexiva sobre la entidad débil.",
   contexto="Año 2050: tras una invasión zombi, los supervivientes se organizan en grupos y el informático superviviente quiere una base de datos con ellos.",
   enun=["Se necesita almacenar información sobre cada **grupo**, los **integrantes** que lo componen, las **tareas** (proyectos) que realiza y sus **trabajadores**.",
         "De los grupos se guarda el identificador, la denominación, la dirección, la provincia y el tipo (recolectores, creadores de munición, atacantes…).",
         "Cada grupo está formado por integrantes, de los que se conoce el DNI, el nombre, la dirección, la provincia, la fecha de alta en el grupo, la cuota mensual con que colaboran y la aportación anual (que se obtiene multiplicando la cuota mensual por los meses del año).",
         "Los grupos tienen también **trabajadores**. Cada trabajador se identifica por un ID y tiene un nombre y una fecha de ingreso. Los trabajadores son de dos tipos: **mantenidos**, que cobran un sueldo en especie y ocupan un cargo (se guarda la cantidad total que se les ha dado), y **voluntarios**, de los que se guarda la edad, la profesión y las horas que dedican al grupo. Un integrante no puede ser trabajador del grupo.",
         "Los grupos realizan **tareas**. Cada tarea se identifica por un número **dentro del grupo** y se guarda en qué zona libre de zombis se realiza y en qué parte de ella, el objetivo y el número de beneficiarios. Una tarea se compone a su vez de **subtareas**, que también son tareas."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica la especialización de `TRABAJADOR` y justifícala.",
           "Indica qué atributo es derivado y cómo se calcula.",
           "Modela las subtareas y escribe el identificador completo de `TAREA`.",
           "Escribe las restricciones que el diagrama no puede expresar."],
   comp=["`TRABAJADOR` se especializa en `MANTENIDO` y `VOLUNTARIO` con **T,D**.",
         "`aportación_anual` es derivado (óvalo discontinuo).",
         "`TAREA` es débil de `GRUPO` (etiqueta ID).",
         "*Se compone de* es una reflexiva 1:N sobre `TAREA`."],
   err=["Crear una entidad `SUBTAREA`: una subtarea es una tarea, se modela con una relación reflexiva.",
        "Guardar la aportación anual: se calcula como `cuota_mensual × 12`.",
        "Poner `edad` y `profesión` en `TRABAJADOR`: solo los tienen los voluntarios."],
   amp="Un integrante puede pertenecer a **varios grupos** con una cuota distinta en cada uno. ¿Qué cambia en la relación *forma parte de*? ¿Dónde van ahora `fecha_alta`, `cuota_mensual` y `aportación_anual`?",
   dec=["Especialización **total y disjunta**: todo trabajador es mantenido o voluntario, nunca ambos.",
        "*Forma parte de* y *trabaja en* son 1:N con `GRUPO`.",
        "`TAREA` se identifica por (id del grupo, nº de tarea). *Se compone de* es reflexiva 1:N con los roles *tarea* y *subtarea*.",
        "«Un integrante no puede ser trabajador» no se representa en el diagrama: integrantes y trabajadores son entidades distintas con identificadores distintos. Se documenta como restricción textual."],
   sup=["Todo integrante pertenece a un grupo: (1,1).",
        "Una subtarea pertenece al mismo grupo que su tarea (restricción textual).",
        "Una persona no puede ser a la vez integrante y trabajador (restricción textual).",
        "Las horas de los voluntarios son un número positivo."],
   model=Model("Grupos de supervivientes del apocalipsis zombi",
               "INTEGRANTE forma parte de GRUPO. TRABAJADOR trabaja en GRUPO y se especializa (T,D) en MANTENIDO y VOLUNTARIO. GRUPO realiza TAREA (débil). TAREA se compone de TAREA.",
               [E("GRUPO", [K("id_grupo"), A("denominación"), A("dirección"), A("provincia"), A("tipo")]),
                E("INTEGRANTE", [K("dni"), A("nombre"), A("dirección"), A("provincia"), A("fecha_alta"), A("cuota_mensual"), D("aportación_anual")]),
                E("TRABAJADOR", [K("id_trabajador"), A("nombre"), A("fecha_ingreso")]),
                E("MANTENIDO", [A("cargo"), A("cantidad_total")]),
                E("VOLUNTARIO", [A("edad"), A("profesión"), A("horas")]),
                E("TAREA", [KP("nº_tarea"), A("zona_libre"), A("zona"), A("objetivo"), A("nº_beneficiarios")], weak=True)],
               [R("forma parte de", [("GRUPO", "(1,1)", None), ("INTEGRANTE", "(1,N)", None)]),
                R("trabaja en", [("GRUPO", "(1,1)", None), ("TRABAJADOR", "(0,N)", None)]),
                R("realiza", [("GRUPO", "(1,1)", None), ("TAREA", "(0,N)", None)], ident=True),
                R("se compone de", [("TAREA", "(0,1)", "tarea"), ("TAREA", "(0,N)", "subtarea")])],
               [ISA("TRABAJADOR", ["MANTENIDO", "VOLUNTARIO"], "d", True)]))
