# -*- coding: utf-8 -*-
"""Banco de ejercicios UD02 · bloques 3 y 4 (ejercicios 13-25)."""
from chen_eer import *

EJS = []


def ej(**kw):
    EJS.append(kw)


# ============================================================ BLOQUE 3
ej(n=13, titulo="Transporte urbano: líneas, paradas y turnos", nivel=3, dur="1-2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + análisis de la ternaria",
   objetivo="Introducir una relación **ternaria** junto a una entidad débil y una N:M reflexiva con atributos.",
   contexto="La empresa municipal de autobuses gestiona su red, su flota y los turnos de conducción.",
   enun=["De las **líneas** se conoce el código (L1, L5…), el nombre del trayecto y la frecuencia de paso en minutos.",
         "Cada línea hace sus paradas en un orden. Cada **parada** se identifica por su número de orden dentro de la línea (1, 2, 3…); se guarda el nombre de la calle o marquesina y si tiene pantalla de información.",
         "Entre líneas se habilitan **transbordos**, con el tiempo estimado a pie entre las dos líneas conectadas.",
         "De los **autobuses** se guarda la matrícula, el modelo y la capacidad de pasajeros de pie. De los **conductores**, el DNI, el nombre y el tipo de licencia. Un conductor conduce un autobús asignado a una línea en un **turno** de trabajo concreto."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Modela *conduce* como relación **ternaria** (conductor, autobús, línea) con el atributo `turno`. Indica su cardinalidad (N:M:P) y explica qué pasaría con tres relaciones binarias.",
           "Razona por qué `PARADA` es débil y por qué *transbordo* es reflexiva con atributo.",
           "Escribe dos restricciones: una sobre el número mínimo de paradas y otra sobre los turnos."],
   comp=["*Conduce* es un único rombo conectado a tres entidades.",
         "`PARADA` es débil de `LÍNEA`; su discriminador es el número de orden.",
         "*Transbordo* tiene el atributo `tiempo_a_pie`.",
         "Has explicado qué información se pierde con tres binarias."],
   err=["Dibujar tres relaciones binarias (conductor–autobús, autobús–línea, conductor–línea): no sabrías quién conducía qué autobús en qué línea.",
        "Colocar `turno` en `CONDUCTOR`. El turno depende de la combinación de los tres."],
   pista=("Pista: ¿ternaria o binarias?",
          "Si el hecho «el conductor C conduce el autobús A en la línea L en el turno T» no se puede reconstruir a partir de tres hechos parciales, necesitas la ternaria. Prueba con dos conductores, dos autobuses y dos líneas."),
   amp="El transbordo se produce realmente **entre paradas**, no entre líneas. Redibuja la relación entre `PARADA` y `PARADA` y razona cómo se identifica ahora.",
   dec=["*Conduce* es ternaria porque el hecho involucra a las tres entidades a la vez y no se puede descomponer.",
        "*Tiene* (línea–parada) es identificadora; una línea tiene al menos dos paradas.",
        "*Transbordo* es una N:M reflexiva con `tiempo_a_pie`; los roles son los dos extremos de la conexión."],
   sup=["Cada línea tiene como mínimo dos paradas: (2,N).",
        "Un autobús puede cambiar de línea de un turno a otro.",
        "El tiempo de transbordo es simétrico entre líneas.",
        "Un conductor no puede conducir dos autobuses en el mismo turno (restricción textual)."],
   model=Model("Transporte urbano: líneas, paradas y turnos",
               "LÍNEA tiene PARADA (débil). LÍNEA se conecta con LÍNEA mediante transbordo. CONDUCTOR, AUTOBÚS y LÍNEA se relacionan en conduce (ternaria) con el turno.",
               [E("LÍNEA", [K("cód_línea"), A("trayecto"), A("frecuencia_min")]),
                E("PARADA", [KP("nº_orden"), A("calle"), A("pantalla")], weak=True),
                E("AUTOBÚS", [K("matrícula"), A("modelo"), A("capacidad_pie")]),
                E("CONDUCTOR", [K("dni"), A("nombre"), A("tipo_licencia")])],
               [R("tiene", [("LÍNEA", "(1,1)", None), ("PARADA", "(2,N)", None)], ident=True),
                R("transbordo", [("LÍNEA", "(0,N)", "origen"), ("LÍNEA", "(0,N)", "destino")], [A("tiempo_a_pie")]),
                R("conduce", [("CONDUCTOR", "(0,N)", None), ("AUTOBÚS", "(0,N)", None), ("LÍNEA", "(0,N)", None)], [KP("turno")])]))

ej(n=14, titulo="Federación deportiva: equipos, partidos e incidencias", nivel=3, dur="1-2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Modelar **dos relaciones entre las mismas entidades** (local y visitante), una relación circular (capitán) y una entidad débil con discriminador compuesto.",
   contexto="Una federación deportiva informatiza el control de sus competiciones oficiales.",
   enun=["De los **equipos** se conoce el código, el nombre del club y la ciudad. De los **jugadores**, el número de ficha federativa, el DNI, el nombre y el dorsal. Un jugador pertenece a un único equipo y cada equipo designa a uno de sus jugadores como **capitán**.",
         "De los **partidos** se guarda el código, la fecha y hora y la jornada. En cada partido se enfrentan dos equipos distintos: uno como **local** y otro como **visitante**.",
         "En el acta de cada partido se registran las **incidencias**. Cada incidencia se identifica por el minuto de juego y un número de secuencia dentro del partido; se anota el tipo (*gol*, *tarjeta amarilla*, *expulsión* o *sustitución*) y el jugador que protagoniza la acción. Si se anula un partido, se eliminan las incidencias de su acta."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Explica por qué entre `EQUIPO` y `PARTIDO` hay **dos** relaciones y no una con un atributo `rol`.",
           "Escribe el identificador de `INCIDENCIA` y razona por qué el discriminador tiene dos atributos.",
           "Escribe al menos tres restricciones que el diagrama no recoge (capitán del propio equipo, local distinto de visitante, jugador de uno de los dos equipos)."],
   comp=["Hay dos relaciones con roles distintos entre `EQUIPO` y `PARTIDO`.",
         "*Capitán* es 1:1 y distinta de *pertenece*.",
         "`INCIDENCIA` es débil de `PARTIDO` con discriminador (minuto, número de secuencia).",
         "Has escrito la restricción «el jugador pertenece a uno de los equipos del partido»."],
   err=["Relacionar `PARTIDO` con `EQUIPO` mediante una sola N:M: no distingues quién juega en casa.",
        "Usar solo el minuto como discriminador: puede haber dos incidencias en el mismo minuto."],
   amp="La federación quiere guardar los **jugadores convocados** en cada partido y los minutos que juega cada uno. ¿Qué relación añades y con qué atributos? ¿Cómo se relaciona con la incidencia?",
   dec=["*Local* y *visitante* son dos relaciones 1:N entre `EQUIPO` y `PARTIDO`: dan información distinta.",
        "*Capitán* (1:1) y *pertenece* (1:N) son relaciones distintas entre `JUGADOR` y `EQUIPO`.",
        "`INCIDENCIA` es débil de `PARTIDO`: (código de partido, minuto, nº de secuencia)."],
   sup=["Todo partido tiene equipo local y visitante: (1,1) en cada relación.",
        "Una incidencia la protagoniza un único jugador.",
        "El capitán pertenece al equipo que capitanea (restricción textual).",
        "El equipo local y el visitante de un partido son distintos (restricción textual)."],
   model=Model("Federación deportiva: equipos, partidos e incidencias",
               "JUGADOR pertenece a EQUIPO y un jugador es capitán. EQUIPO es local o visitante en PARTIDO. PARTIDO registra INCIDENCIA (débil) protagonizada por JUGADOR.",
               [E("EQUIPO", [K("cód_equipo"), A("club"), A("ciudad")]),
                E("JUGADOR", [K("nº_ficha"), A("dni"), A("nombre"), A("dorsal")]),
                E("PARTIDO", [K("cód_partido"), A("fecha_hora"), A("jornada")]),
                E("INCIDENCIA", [KP("minuto"), KP("nº_secuencia"), A("tipo")], weak=True)],
               [R("pertenece a", [("EQUIPO", "(1,1)", None), ("JUGADOR", "(1,N)", None)]),
                R("capitán", [("JUGADOR", "(1,1)", None), ("EQUIPO", "(0,1)", None)]),
                R("local", [("EQUIPO", "(1,1)", None), ("PARTIDO", "(0,N)", None)]),
                R("visitante", [("EQUIPO", "(1,1)", None), ("PARTIDO", "(0,N)", None)]),
                R("registra", [("PARTIDO", "(1,1)", None), ("INCIDENCIA", "(0,N)", None)], ident=True),
                R("protagoniza", [("JUGADOR", "(1,1)", None), ("INCIDENCIA", "(0,N)", None)])]))

ej(n=15, titulo="Red de gimnasios: salas, reservas y entrenadores", nivel=3, dur="1-2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Gestionar varias relaciones N:M con atributos repetibles junto a una entidad débil y una supervisión reflexiva.",
   contexto="Una cadena de gimnasios gestiona sus centros, sus socios y los entrenamientos personalizados.",
   enun=["De cada **gimnasio** se conoce el código, el nombre comercial, la dirección, la ciudad y la superficie en m².",
         "Cada gimnasio dispone de **salas**. Cada sala se identifica por un número o letra propio del gimnasio (101, Sala A…); se guarda el tipo de actividad (*musculación*, *cardio*, *pilates*, *spinning*) y el aforo máximo.",
         "De los **socios** se almacena el número, el DNI, el nombre, los apellidos, el teléfono y la fecha de alta. Un socio está inscrito en un gimnasio principal, pero puede reservar plaza en las salas de cualquier centro de la cadena (se registra la fecha, la hora y la plaza).",
         "De los **entrenadores** se conoce el código de empleado, el nombre, la especialidad y la titulación. Cada entrenador trabaja en un gimnasio y diseña **rutinas** para los socios, con la fecha de asignación y el objetivo. En cada gimnasio, un **director técnico** coordina al resto de entrenadores."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Distingue las dos relaciones entre `SOCIO` y `GIMNASIO`/`SALA`: la inscripción y la reserva. Justifica sus cardinalidades.",
           "Identifica qué atributos de las dos relaciones N:M permiten que se repitan entre las mismas entidades.",
           "Escribe tres restricciones textuales (aforo, un único director por gimnasio, reservas solapadas)."],
   comp=["`SALA` es débil de `GIMNASIO`.",
         "*Reserva* conecta `SOCIO` con `SALA` y la fecha y la hora forman parte de su identificación.",
         "*Diseña* es N:M con `fecha_asignación` y `objetivo`.",
         "*Dirige* es una relación reflexiva sobre `ENTRENADOR`."],
   err=["Relacionar `SOCIO` con `GIMNASIO` para las reservas. La reserva se hace sobre una sala concreta.",
        "Olvidar que un socio puede reservar la misma sala muchas veces."],
   amp="Las reservas de clase **tienen un entrenador** responsable. ¿La reserva pasa a ser una ternaria o puede resolverse con una binaria adicional? Razona con el aforo y la sesión.",
   dec=["La inscripción (socio → gimnasio) es 1:N; la reserva es N:M entre `SOCIO` y `SALA` con fecha, hora y plaza.",
        "`SALA` se identifica por (código de gimnasio, número de sala).",
        "El director técnico es un entrenador que coordina a otros: relación reflexiva 1:N con roles."],
   sup=["Un gimnasio tiene al menos una sala.",
        "Un entrenador trabaja en un único gimnasio.",
        "En cada gimnasio hay un solo director técnico (restricción textual).",
        "El número de reservas de una sala en una franja no supera su aforo (restricción textual)."],
   model=Model("Red de gimnasios: salas, reservas y entrenadores",
               "GIMNASIO dispone de SALA (débil). SOCIO se inscribe en GIMNASIO y reserva SALA. ENTRENADOR trabaja en GIMNASIO, diseña rutinas para SOCIO y es dirigido por otro ENTRENADOR.",
               [E("GIMNASIO", [K("cód_centro"), A("nombre"), A("dirección"), A("ciudad"), A("superficie_m2")]),
                E("SALA", [KP("nº_sala"), A("actividad"), A("aforo")], weak=True),
                E("SOCIO", [K("nº_socio"), A("dni"), A("nombre"), A("apellidos"), A("teléfono"), A("fecha_alta")]),
                E("ENTRENADOR", [K("cód_empleado"), A("nombre"), A("especialidad"), A("titulación")])],
               [R("dispone de", [("GIMNASIO", "(1,1)", None), ("SALA", "(1,N)", None)], ident=True),
                R("se inscribe en", [("GIMNASIO", "(1,1)", None), ("SOCIO", "(0,N)", None)]),
                R("reserva", [("SOCIO", "(0,N)", None), ("SALA", "(0,N)", None)], [KP("fecha"), KP("hora"), A("plaza")]),
                R("trabaja en", [("ENTRENADOR", "(1,N)", None), ("GIMNASIO", "(1,1)", None)]),
                R("diseña", [("ENTRENADOR", "(0,N)", None), ("SOCIO", "(0,N)", None)], [KP("fecha_asignación"), A("objetivo")]),
                R("dirige", [("ENTRENADOR", "(0,1)", "director"), ("ENTRENADOR", "(0,N)", "entrenador")])]))

ej(n=16, titulo="Repostería PAVA S.A.: recetas, formatos, pedidos y competencia", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario de datos",
   objetivo="Resolver un caso con siete entidades, una composición con porcentajes y un formato dependiente del producto.",
   contexto="Una gran empresa de dulces necesita una base de datos centralizada para su producción, ventas y promociones.",
   enun=["La empresa elabora productos a partir de **ingredientes**. De cada ingrediente se conoce el nombre (único), la cantidad de vitaminas A, B y C por cada 100 g, las calorías y el coste por kilo.",
         "Con ellos fabrica **productos** («Filipondios», «Barridulces»…), conocidos por su nombre comercial. Interesa la composición de cada producto y el **porcentaje** de cada ingrediente en la receta.",
         "Cada producto se comercializa en **formatos** de peso (40 g, 150 g, 250 g…), y cada formato tiene un precio de venta.",
         "De los **clientes** se guarda el CIF, el nombre, la dirección, la población, la provincia y el teléfono. Los clientes hacen **pedidos** de unidades de productos en formatos concretos (200 unidades de Barridulces en formato de 250 g).",
         "La empresa prevé las **promociones** del año («2x1», «Vale descuento»). Cada tipo de promoción se pone en marcha una vez al año, con fecha de inicio, fecha de fin y la cantidad máxima de productos de cada formato que pueden beneficiarse.",
         "Por último, se registran los **productos competidores** (nombre comercial único, marca y año de lanzamiento), vinculando cada uno al producto de la empresa al que más se parece."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Decide si el formato es una entidad débil de `PRODUCTO` o una entidad independiente. Justifícalo con un ejemplo (40 g de Barridulces frente a 40 g de Filipondios).",
           "Elabora el **diccionario de datos** de `INGREDIENTE` y de la relación de composición.",
           "Escribe tres restricciones: suma de porcentajes, cantidad máxima de promoción y fechas."],
   comp=["La composición es una N:M con atributo `porcentaje`.",
         "El formato depende del producto: `FORMATO` es una entidad débil.",
         "El pedido se relaciona con el **formato**, no solo con el producto.",
         "*Se parece a* es 1:N desde el producto hacia los competidores."],
   err=["Relacionar `PEDIDO` con `PRODUCTO` sin indicar el formato. No sabrías qué se ha pedido.",
        "Poner el precio en `PRODUCTO`: cada formato tiene el suyo."],
   amp="El **precio** de cada formato cambia con el tiempo y se quiere conservar el histórico. ¿Qué entidad o atributo añadirías? ¿Dónde se guardaría el precio con el que se vendió cada pedido?",
   dec=["`FORMATO` es débil de `PRODUCTO`: (nombre comercial, peso).",
        "*Se compone de* es N:M con `porcentaje`; el porcentaje depende de la pareja producto-ingrediente.",
        "*Solicita* relaciona `PEDIDO` con `FORMATO` y guarda las unidades; *se aplica a* lo hace con `PROMOCIÓN` y guarda la cantidad máxima."],
   sup=["Todo producto tiene al menos un ingrediente: (1,N).",
        "Un competidor se parece a un solo producto de la empresa.",
        "Los porcentajes de una receta suman 100 (restricción textual).",
        "La fecha de fin de la promoción no es anterior a la de inicio (restricción textual)."],
   model=Model("Repostería PAVA S.A.",
               "INGREDIENTE forma parte de PRODUCTO con un porcentaje. PRODUCTO tiene FORMATO (débil). CLIENTE hace PEDIDO que solicita FORMATO. PROMOCIÓN se aplica a FORMATO. COMPETIDOR se parece a PRODUCTO.",
               [E("INGREDIENTE", [K("nombre"), A("vitaminas_A_B_C"), A("calorías"), A("coste_kg")]),
                E("PRODUCTO", [K("nombre_comercial")]),
                E("FORMATO", [KP("peso_g"), A("precio_venta")], weak=True),
                E("CLIENTE", [K("cif"), A("nombre"), C("dirección", "calle", "población", "provincia"), A("teléfono")]),
                E("PEDIDO", [K("nº_pedido"), A("fecha")]),
                E("PROMOCIÓN", [K("tipo"), A("fecha_inicio"), A("fecha_fin")]),
                E("COMPETIDOR", [K("nombre_comercial"), A("marca"), A("año_lanzamiento")])],
               [R("se compone de", [("INGREDIENTE", "(1,N)", None), ("PRODUCTO", "(0,N)", None)], [A("porcentaje")]),
                R("tiene", [("PRODUCTO", "(1,1)", None), ("FORMATO", "(1,N)", None)], ident=True),
                R("hace", [("CLIENTE", "(1,1)", None), ("PEDIDO", "(0,N)", None)]),
                R("solicita", [("PEDIDO", "(0,N)", None), ("FORMATO", "(1,N)", None)], [A("unidades")]),
                R("se aplica a", [("PROMOCIÓN", "(0,N)", None), ("FORMATO", "(0,N)", None)], [A("cantidad_máxima")]),
                R("se parece a", [("COMPETIDOR", "(0,N)", None), ("PRODUCTO", "(1,1)", None)])]))

ej(n=17, titulo="Planta industrial: lista de materiales e inspecciones", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Modelar una estructura de **lista de materiales (BOM)** con una N:M reflexiva y detectar restricciones de integridad que el diagrama no recoge (ciclos y borrado).",
   contexto="Una planta de maquinaria pesada gestiona su proceso de producción y sus controles de calidad.",
   enun=["De las **fábricas** se conoce el código, la ubicación y el teléfono. Cada fábrica alberga varias **líneas de montaje**. El código de línea es correlativo dentro de cada fábrica (la línea 1 de Valencia y la línea 1 de Sevilla son distintas) y se guarda la denominación.",
         "De las **piezas** se registra el código, el nombre, el peso en gramos y el coste estándar. Una pieza se ensambla a partir de otras piezas componentes y una pieza puede formar parte de muchas piezas superiores. De cada componente interesa la **cantidad** de unidades necesarias. Cada pieza se fabrica en una línea de montaje.",
         "Cada pieza pasa **inspecciones** de calidad. Cada inspección se identifica con un número dentro de la pieza y guarda la fecha, el resultado (*aprobado* o *rechazado*) y las observaciones. Si una pieza se descataloga, sus inspecciones se eliminan automáticamente."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Explica la relación reflexiva *compone* con sus dos roles y su atributo.",
           "Identifica las **dos** entidades débiles y escribe sus identificadores completos.",
           "Escribe las restricciones: ausencia de ciclos en la lista de materiales, borrado en cascada y dominio del resultado."],
   comp=["*Compone* es una N:M reflexiva con el atributo `cantidad`.",
         "`LÍNEA` e `INSPECCIÓN` son entidades débiles.",
         "La pieza se relaciona con la línea de montaje (que a su vez depende de la fábrica).",
         "Entre las restricciones aparece «una pieza no puede contenerse a sí misma, directa o indirectamente»."],
   err=["Dar a `LÍNEA` un código global: el enunciado dice que es correlativo por fábrica.",
        "Modelar la lista de materiales con una relación 1:N: una pieza componente participa en muchos ensamblajes."],
   amp="Algunas piezas se **compran a proveedores** en lugar de fabricarse. ¿Cómo modelarías esta distinción? Plantea una especialización de `PIEZA` y decide si es total o parcial, disyunta o solapada.",
   dec=["`LÍNEA` se identifica por (código de fábrica, código de línea) e `INSPECCIÓN` por (código de pieza, número).",
        "*Compone* es una reflexiva N:M: una pieza tiene muchos componentes y es componente de muchas piezas.",
        "La pieza se fabrica en una línea: relación N:1 con la entidad débil."],
   sup=["Todas las piezas se fabrican en una línea: (1,1).",
        "Una pieza simple (sin componentes) es válida.",
        "No se admiten ciclos en la lista de materiales (restricción textual).",
        "Al eliminar una pieza se eliminan sus inspecciones (borrado en cascada)."],
   model=Model("Planta industrial: lista de materiales e inspecciones",
               "FÁBRICA alberga LÍNEA (débil). PIEZA se fabrica en una LÍNEA. PIEZA se compone de PIEZA con una cantidad. PIEZA se inspecciona en INSPECCIÓN (débil).",
               [E("FÁBRICA", [K("cód_fábrica"), A("ubicación"), A("teléfono")]),
                E("LÍNEA", [KP("cód_línea"), A("denominación")], weak=True),
                E("PIEZA", [K("cód_pieza"), A("nombre"), A("peso_g"), A("coste_estándar")]),
                E("INSPECCIÓN", [KP("nº_inspección"), A("fecha"), A("resultado"), A("observaciones")], weak=True)],
               [R("alberga", [("FÁBRICA", "(1,1)", None), ("LÍNEA", "(1,N)", None)], ident=True),
                R("se fabrica en", [("PIEZA", "(0,N)", None), ("LÍNEA", "(1,1)", None)]),
                R("compone", [("PIEZA", "(0,N)", "ensamblada"), ("PIEZA", "(0,N)", "componente")], [A("cantidad")]),
                R("se inspecciona", [("PIEZA", "(1,1)", None), ("INSPECCIÓN", "(0,N)", None)], ident=True)]))

ej(n=18, titulo="Comandancia de Starship Troopers", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Combinar siete relaciones con cardinalidades máximas concretas, atributos de N:M y una jerarquía reflexiva.",
   contexto="La comandancia de la fuerza de defensa quiere registrar su operativa interna.",
   enun=["De los **troopers** se conoce el número de placa, el DNI, el nombre, la categoría y la función (piloto, agente…). Cada trooper tiene un único **jefe** directo y un trooper puede ser jefe de varios subordinados.",
         "El arsenal contiene **armas** con código único, clase y nombre. Un trooper puede usar varias armas; interesa la **habilidad** (de 1 a 10) de cada trooper con cada arma.",
         "De los **bichos** capturados se conoce el identificador, la raza, la localización de origen y el peso. Un bicho es detenido por uno o varios troopers y se guarda la **fecha de detención**. El mismo trooper puede detener al mismo bicho en fechas distintas.",
         "Cada bicho que permanece en la comandancia se encierra en una **mazmorra** (código y ubicación). En una mazmorra puede haber varios bichos, **nunca más de cuatro**.",
         "Los bichos participan en **delitos** (número de asalto y juzgado instructor), y se anota el **cargo principal** de cada bicho en cada delito. Uno o varios troopers investigan cada delito."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Escribe las cardinalidades (mín, máx) de las siete relaciones y justifica la de la mazmorra.",
           "Indica qué atributos pertenecen a relaciones N:M y por qué (habilidad, fecha de detención, cargo principal).",
           "Escribe las restricciones: la habilidad entre 1 y 10, y el máximo de cuatro bichos por mazmorra."],
   comp=["La jerarquía de jefes es una reflexiva 1:N.",
         "`cargo_principal` está en la relación *implicado en*.",
         "La mazmorra tiene máximo 4 bichos en la cardinalidad.",
         "`fecha_detención` forma parte de la identificación de *detiene*."],
   err=["Poner `cargo_principal` en `BICHO`: un bicho puede estar implicado en varios delitos con cargos distintos.",
        "Expresar «máximo cuatro» solo en el texto y no en la cardinalidad."],
   amp="Cada trooper tiene una **especialidad** (piloto, agente, médico…) con datos propios. Plantea una **especialización** de `TROOPER`, decide si es total o parcial, disyunta o solapada, y redibuja la parte afectada.",
   dec=["*Jefe* es una reflexiva 1:N; un trooper sin jefe es la cúspide de la cadena.",
        "*Usa*, *detiene*, *implicado en* e *investiga* son N:M. Los tres primeros llevan atributos.",
        "*Encierra* es 1:N con máximo 4 en el lado del bicho: (0,4)."],
   sup=["Un bicho puede estar capturado y no encerrado: (0,1) mazmorra.",
        "Un delito tiene al menos un bicho implicado.",
        "La habilidad es un entero entre 1 y 10 (restricción de dominio).",
        "Una mazmorra no aloja a más de cuatro bichos a la vez (restricción textual)."],
   model=Model("Comandancia de Starship Troopers",
               "TROOPER tiene jefe TROOPER, usa ARMA, detiene BICHO e investiga DELITO. MAZMORRA encierra BICHO. BICHO está implicado en DELITO.",
               [E("TROOPER", [K("nº_placa"), A("dni"), A("nombre"), A("categoría"), A("función")]),
                E("ARMA", [K("cód_arma"), A("clase"), A("nombre")]),
                E("BICHO", [K("id_bicho"), A("raza"), A("origen"), A("peso")]),
                E("MAZMORRA", [K("cód_mazmorra"), A("ubicación")]),
                E("DELITO", [K("nº_asalto"), A("juzgado")])],
               [R("jefe", [("TROOPER", "(0,1)", "jefe"), ("TROOPER", "(0,N)", "subordinado")]),
                R("usa", [("TROOPER", "(0,N)", None), ("ARMA", "(0,N)", None)], [A("habilidad")]),
                R("detiene", [("TROOPER", "(1,N)", None), ("BICHO", "(0,N)", None)], [KP("fecha_detención")]),
                R("encierra", [("MAZMORRA", "(0,1)", None), ("BICHO", "(0,4)", None)]),
                R("implicado en", [("BICHO", "(1,N)", None), ("DELITO", "(0,N)", None)], [A("cargo_principal")]),
                R("investiga", [("TROOPER", "(1,N)", None), ("DELITO", "(0,N)", None)])]))

ej(n=19, titulo="Torneo de Quidditch: jugadores especializados", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + clasificación de la jerarquía",
   objetivo="Ampliar un modelo conocido (ejercicio 14) con una **especialización total y disyunta** con atributos propios.",
   contexto="Una liga mágica celebra un torneo oficial. El modelo parte del de la federación deportiva, pero ahora los jugadores se especializan por puesto.",
   enun=["De cada **equipo** se registra el código, el nombre del club, la casa o colegio al que representa y el año de fundación. Los **jugadores** (número de carné, nombre y apellidos) pertenecen a un único equipo y cada equipo designa a uno como **capitán**.",
         "Cada jugador ocupa un único puesto y de cada puesto se guardan estadísticas propias: los **guardianes**, las paradas; los **golpeadores**, las bludgers golpeadas; los **cazadores**, los goles marcados; los **buscadores**, las capturas de snitch.",
         "De los **partidos** se conoce el código, el estadio, la fecha y hora y el **árbitro** asignado (código y nombre). En cada partido compiten un equipo local y uno visitante.",
         "Durante el partido se registran **incidencias** (infracciones y penaltis), identificadas por el minuto y un número de secuencia dentro del partido. Se anotan el tipo de falta, la puntuación otorgada y el jugador sancionado."],
   tareas=["Dibuja el diagrama EER en notación de Chen con la jerarquía de jugadores.",
           "Clasifica la jerarquía (total o parcial, disyunta o solapada) y justifícalo con una frase del enunciado.",
           "¿Qué ocurre con el atributo `posición` que aparecía en el ejercicio 14? ¿Sigue haciendo falta?",
           "Escribe las restricciones: capitán del propio equipo, local distinto de visitante, árbitro sin vínculo con los equipos."],
   comp=["La especialización es **total y disyunta** y se dibuja con el círculo `d` y doble línea hacia la superclase.",
         "Los atributos comunes están en `JUGADOR` y las estadísticas, en cada subclase.",
         "El árbitro es una entidad relacionada con el partido.",
         "`INCIDENCIA` es débil de `PARTIDO`."],
   err=["Repetir los atributos comunes (nombre, carné…) en cada subclase.",
        "Mantener un atributo `posición` además de la especialización: duplica la información y puede contradecirse."],
   amp="Algunos jugadores pueden ocupar **dos puestos** en la misma temporada (cazador y buscador). ¿Qué cambia en la clasificación de la jerarquía? ¿Cómo la dibujarías?",
   dec=["Hay cuatro subclases con una sola jerarquía **total y disyunta**: cada jugador ocupa un puesto y solo uno.",
        "El atributo `posición` desaparece: la pertenencia a una subclase la expresa.",
        "El resto del modelo (capitán, local, visitante, incidencias) es el del ejercicio 14, más la entidad `ÁRBITRO`."],
   sup=["Todo jugador tiene un puesto: especialización total.",
        "Un partido tiene un único árbitro: (1,1).",
        "El jugador sancionado pertenece a uno de los dos equipos del partido (restricción textual).",
        "El capitán pertenece a su equipo (restricción textual)."],
   model=Model("Torneo de Quidditch: jugadores especializados",
               "JUGADOR se especializa (d, total) en GUARDIÁN, GOLPEADOR, CAZADOR y BUSCADOR. EQUIPO tiene JUGADOR y capitán, juega PARTIDO como local y visitante. ÁRBITRO arbitra PARTIDO. PARTIDO registra INCIDENCIA.",
               [E("EQUIPO", [K("cód_equipo"), A("club"), A("casa_colegio"), A("año_fundación")]),
                E("JUGADOR", [K("nº_carné"), A("nombre"), A("apellidos")]),
                E("GUARDIÁN", [A("paradas")]), E("GOLPEADOR", [A("bludgers")]),
                E("CAZADOR", [A("goles")]), E("BUSCADOR", [A("snitch")]),
                E("PARTIDO", [K("cód_partido"), A("estadio"), A("fecha_hora")]),
                E("ÁRBITRO", [K("cód_árbitro"), A("nombre")]),
                E("INCIDENCIA", [KP("minuto"), KP("nº_secuencia"), A("tipo_falta"), A("puntos")], weak=True)],
               [R("pertenece a", [("EQUIPO", "(1,1)", None), ("JUGADOR", "(1,N)", None)]),
                R("capitán", [("JUGADOR", "(1,1)", None), ("EQUIPO", "(0,1)", None)]),
                R("local", [("EQUIPO", "(1,1)", None), ("PARTIDO", "(0,N)", None)]),
                R("visitante", [("EQUIPO", "(1,1)", None), ("PARTIDO", "(0,N)", None)]),
                R("arbitra", [("ÁRBITRO", "(1,1)", None), ("PARTIDO", "(0,N)", None)]),
                R("registra", [("PARTIDO", "(1,1)", None), ("INCIDENCIA", "(0,N)", None)], ident=True),
                R("sanciona a", [("JUGADOR", "(1,1)", None), ("INCIDENCIA", "(0,N)", None)])],
               [ISA("JUGADOR", ["GUARDIÁN", "GOLPEADOR", "CAZADOR", "BUSCADOR"], "d", True)]))

# ============================================================ BLOQUE 4
ej(n=20, titulo="Seguridad bancaria: vigilantes, bandas y atracos", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario + restricciones",
   objetivo="Integrar una especialización con atributos propios, una ternaria con atributos, una reflexiva y un atributo derivado.",
   contexto="La Policía y la asociación de entidades bancarias quieren una base de datos sobre seguridad y delitos.",
   enun=["De las **entidades bancarias** se conoce el código y la dirección de la sede. Una entidad tiene varias **sucursales**, identificadas por un código dentro de la entidad, con dirección y número de empleados.",
         "Las sucursales contratan **vigilantes**: código, DNI, nombre y fecha de nacimiento (la edad se calcula). Un vigilante es obligatoriamente **armado** (puntuación de tiro y calibre) o **no armado** (si tiene titulación en artes marciales). Un vigilante puede ser contratado por distintas sucursales en fechas diferentes y se registra si el contrato es con arma o no.",
         "Se controla a los **detenidos** por atracar sucursales (código y nombre completo). Algunos pertenecen a **bandas** (número y número de miembros). Una banda puede estar subordinada a otra banda matriz.",
         "Cada **atraco** vincula al detenido, a la sucursal atracada y al **juez** instructor (clave del juzgado, nombre y años de servicio), con la fecha, la condena en años y la indemnización."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica la jerarquía de vigilantes y explica dónde se coloca cada atributo.",
           "Modela el atraco como **ternaria** y razona sus cardinalidades. ¿Qué atributo permite repetir la misma terna?",
           "Escribe el diccionario de datos de `VIGILANTE` y tres restricciones: contrato con arma solo para armados, `num_miembros` coherente y condena no negativa."],
   comp=["La especialización es **total y disyunta**.",
         "`edad` y `num_miembros` son atributos derivados.",
         "*Atraco* es una ternaria con `fecha`, `condena` e `indemnización`.",
         "`SUCURSAL` es débil de `ENTIDAD_BANCARIA`."],
   err=["Guardar `edad` como atributo normal: cambia cada año.",
        "No relacionar el contrato con la especialización: un contrato «con arma» solo puede firmarlo un vigilante armado."],
   amp="Un detenido puede pertenecer a **varias bandas** a lo largo del tiempo. ¿Qué atributo necesita ahora la relación y cómo cambia la reflexiva de subordinación?",
   dec=["Especialización de `VIGILANTE`: total y disyunta, con atributos propios en cada subclase.",
        "*Contrata* es N:M entre `SUCURSAL` y `VIGILANTE` con `fecha_inicio` y `con_arma`.",
        "*Atraco* es ternaria (detenido, sucursal, juez) y la fecha forma parte de su identificación."],
   sup=["Todo vigilante es armado o no armado.",
        "Un detenido puede no pertenecer a ninguna banda.",
        "Un contrato con arma solo es válido para vigilantes armados (restricción textual).",
        "`num_miembros` equivale al número de detenidos de la banda (atributo derivado)."],
   model=Model("Seguridad bancaria: vigilantes, bandas y atracos",
               "ENTIDAD tiene SUCURSAL (débil). SUCURSAL contrata VIGILANTE, que es armado o no armado. DETENIDO pertenece a BANDA, que puede ser subordinada de otra. DETENIDO, SUCURSAL y JUEZ se relacionan en atraco.",
               [E("ENTIDAD", [K("cód_entidad"), A("dir_sede")]),
                E("SUCURSAL", [KP("cód_sucursal"), A("dirección"), A("nº_empleados")], weak=True),
                E("VIGILANTE", [K("cód_vigilante"), A("dni"), A("nombre"), A("fecha_nacimiento"), D("edad")]),
                E("ARMADO", [A("puntuación_tiro"), A("calibre")]),
                E("NO_ARMADO", [A("titulación_artes")]),
                E("DETENIDO", [K("cód_detenido"), A("nombre_completo")]),
                E("BANDA", [K("nº_banda"), D("nº_miembros")]),
                E("JUEZ", [K("clave_juzgado"), A("nombre"), A("años_servicio")])],
               [R("tiene", [("ENTIDAD", "(1,1)", None), ("SUCURSAL", "(1,N)", None)], ident=True),
                R("contrata", [("SUCURSAL", "(0,N)", None), ("VIGILANTE", "(0,N)", None)], [KP("fecha_inicio"), A("con_arma")]),
                R("pertenece a", [("BANDA", "(0,1)", None), ("DETENIDO", "(0,N)", None)]),
                R("subordinada", [("BANDA", "(0,1)", "matriz"), ("BANDA", "(0,N)", "subordinada")]),
                R("atraco", [("DETENIDO", "(0,N)", None), ("SUCURSAL", "(0,N)", None), ("JUEZ", "(0,N)", None)],
                  [KP("fecha"), A("condena_años"), A("indemnización")])],
               [ISA("VIGILANTE", ["ARMADO", "NO_ARMADO"], "d", True)]))

ej(n=21, titulo="Club hípico: caballos, boxes y lecciones", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario + restricciones",
   objetivo="Modelar dos especializaciones, una genealogía reflexiva, una cadena de entidad débil y una ternaria de lecciones.",
   contexto="Un club hípico gestiona su cuadra, sus socios, sus instructores y las clases de equitación.",
   enun=["De los **caballos** se conoce el microchip, el nombre, la raza y la fecha de nacimiento. Son **propios del club** (fecha de adquisición y coste mensual de mantenimiento) o **de un socio** (cuota de pupilaje y socio propietario). Se mantiene la **genealogía**: un caballo puede ser progenitor (padre o madre) de varios potros nacidos en el club.",
         "Los establos se dividen en **pabellones** (código y nombre). Cada pabellón tiene varios **boxes**, numerados correlativamente dentro del pabellón (Box 1, Box 2…). Cada caballo ocupa un único box y un box aloja como máximo un caballo.",
         "De los **socios** se guarda el DNI y el nombre. De los **instructores**, el número de colegiado, el DNI, el nombre y la titulación. Son **titulares** o **en prácticas**; cada instructor en prácticas es supervisado por un titular.",
         "Las **lecciones** reúnen a un socio, un instructor y un caballo, con la fecha, la hora, la pista y el nivel (*iniciación*, *doma* o *salto*)."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica las dos jerarquías y justifica por qué la relación con el socio propietario sale de una subclase y no de `CABALLO`.",
           "Modela la lección como ternaria y calcula sus cardinalidades.",
           "Escribe el diccionario de datos de `CABALLO` y tres restricciones (dos progenitores como máximo, instructor en prácticas supervisado, box libre)."],
   comp=["Hay dos jerarquías **totales y disyuntas**.",
         "La genealogía es una reflexiva con máximo 2 progenitores por potro.",
         "`BOX` es débil de `PABELLÓN`.",
         "*Supervisa* sale de la subclase *en prácticas* hacia *titular*."],
   err=["Relacionar `SOCIO` con todos los caballos: solo con los que son de socio.",
        "Dibujar la genealogía como 1:N: un potro tiene dos progenitores."],
   amp="Un caballo cambia de box con el tiempo y se quiere conservar el **historial de ubicaciones**. ¿Qué relación pasa a ser N:M y con qué atributos?",
   dec=["`CABALLO` se especializa en propio y de socio; `INSTRUCTOR`, en titular y en prácticas.",
        "*Genealogía*: reflexiva N:M con máximo 2 en el rol de progenitor.",
        "*Lección*: ternaria con fecha y hora en su identificación."],
   sup=["Todo caballo es del club o de un socio.",
        "Un potro tiene como máximo dos progenitores registrados.",
        "Un instructor en prácticas tiene un único titular supervisor.",
        "Un caballo no recibe dos lecciones a la misma hora (restricción textual)."],
   model=Model("Club hípico: caballos, boxes y lecciones",
               "CABALLO se especializa en propio y de socio y tiene genealogía. PABELLÓN tiene BOX (débil), ocupado por un caballo. INSTRUCTOR se especializa en titular y en prácticas. SOCIO, INSTRUCTOR y CABALLO se relacionan en lección.",
               [E("CABALLO", [K("microchip"), A("nombre"), A("raza"), A("fecha_nacimiento")]),
                E("DEL_CLUB", [A("fecha_adquisición"), A("coste_mensual")]),
                E("DE_SOCIO", [A("cuota_pupilaje")]),
                E("SOCIO", [K("dni"), A("nombre")]),
                E("PABELLÓN", [K("cód_pabellón"), A("nombre")]),
                E("BOX", [KP("nº_box")], weak=True),
                E("INSTRUCTOR", [K("nº_colegiado"), A("dni"), A("nombre"), A("titulación")]),
                E("TITULAR", []), E("EN_PRÁCTICAS", [])],
               [R("genealogía", [("CABALLO", "(0,2)", "progenitor"), ("CABALLO", "(0,N)", "potro")]),
                R("es propiedad de", [("SOCIO", "(1,1)", None), ("DE_SOCIO", "(0,N)", None)]),
                R("contiene", [("PABELLÓN", "(1,1)", None), ("BOX", "(1,N)", None)], ident=True),
                R("ocupa", [("CABALLO", "(0,1)", None), ("BOX", "(1,1)", None)]),
                R("supervisa", [("TITULAR", "(1,1)", None), ("EN_PRÁCTICAS", "(0,N)", None)]),
                R("lección", [("SOCIO", "(0,N)", None), ("INSTRUCTOR", "(0,N)", None), ("CABALLO", "(0,N)", None)],
                  [KP("fecha"), KP("hora"), A("pista"), A("nivel")])],
               [ISA("CABALLO", ["DEL_CLUB", "DE_SOCIO"], "d", True),
                ISA("INSTRUCTOR", ["TITULAR", "EN_PRÁCTICAS"], "d", True)]))

ej(n=22, titulo="Hotel-balneario: alojados, habitaciones y tratamientos", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario + restricciones",
   objetivo="Combinar dos especializaciones, una especialización parcial con reflexiva, una entidad débil y una ternaria con atributos.",
   contexto="Un hotel-balneario termal automatiza la gestión de huéspedes, instalaciones y tratamientos.",
   enun=["De los **clientes** se almacena el DNI, el nombre, los apellidos y la fecha de nacimiento. Son **alojados** (tarjeta de crédito y fecha de salida prevista) o **ambulantes** (teléfono de emergencia), y no pueden ser ambas cosas.",
         "El hotel se divide en **plantas** (número, nombre y número de habitaciones). Las **habitaciones** se numeran correlativamente dentro de cada planta (existe la habitación 1 de la planta 3 y la habitación 1 de la 8) y tienen una capacidad. Son **suites** (jacuzzis y metros cuadrados) o **estándar** (si admiten cama supletoria y el tipo de baño). Un cliente alojado se asigna a una habitación en una fecha.",
         "De los **empleados** se conoce el código, el nombre y el puesto. Algunos son **terapeutas**, y entre ellos existe una jerarquía: un terapeuta *senior* coordina a terapeutas *junior*.",
         "Los **tratamientos** (código y nombre) se prestan de forma conjunta entre el cliente, el terapeuta y el tratamiento, con la fecha, la hora, la duración y las observaciones médicas."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica las tres jerarquías (cliente, habitación, empleado) y justifica cada clasificación con una frase del enunciado.",
           "Razona por qué el número de habitaciones de la planta es un atributo derivado y por qué la habitación es débil.",
           "Escribe el diccionario de datos de `CLIENTE` y tres restricciones (solo los alojados se asignan a habitación, capacidad, fecha de salida)."],
   comp=["La jerarquía de empleados es **parcial** y las otras dos son **totales y disyuntas**.",
         "*Asignación* sale de la subclase `ALOJADO`.",
         "`HABITACIÓN` es débil de `PLANTA`.",
         "*Presta* es una ternaria con cuatro atributos."],
   err=["Relacionar la habitación con `CLIENTE` en lugar de con `ALOJADO`: un ambulante no tiene habitación.",
        "Hacer que todos los empleados sean terapeutas: la jerarquía es parcial."],
   amp="Una suite puede **reformarse** y pasar a estándar. ¿Es compatible con una especialización disyunta? ¿Qué decisión de diseño habría que tomar?",
   dec=["Tres jerarquías: clientes (total, disyunta), habitaciones (total, disyunta) y empleados (parcial).",
        "`HABITACIÓN` depende de `PLANTA`; `nº_habitaciones` es derivado.",
        "*Presta* es ternaria (cliente, terapeuta, tratamiento) con fecha y hora."],
   sup=["Todo cliente es alojado o ambulante.",
        "Un terapeuta senior coordina a varios juniors; un junior tiene como mucho un coordinador.",
        "Solo los alojados tienen habitación asignada (restricción textual).",
        "La fecha de salida prevista es posterior a la de asignación (restricción textual)."],
   model=Model("Hotel-balneario: alojados, habitaciones y tratamientos",
               "CLIENTE se especializa en alojado o ambulante. PLANTA tiene HABITACIÓN (débil), que es suite o estándar. EMPLEADO puede ser TERAPEUTA, que coordina a otros terapeutas. CLIENTE, TERAPEUTA y TRATAMIENTO se relacionan en presta.",
               [E("CLIENTE", [K("dni"), A("nombre"), A("apellidos"), A("fecha_nacimiento")]),
                E("ALOJADO", [A("nº_tarjeta"), A("fecha_salida")]),
                E("AMBULANTE", [A("tel_emergencia")]),
                E("PLANTA", [K("nº_planta"), A("nombre"), D("nº_habitaciones")]),
                E("HABITACIÓN", [KP("nº_habitación"), A("capacidad")], weak=True),
                E("SUITE", [A("jacuzzis"), A("metros2")]),
                E("ESTÁNDAR", [A("cama_supletoria"), A("tipo_baño")]),
                E("EMPLEADO", [K("cód_empleado"), A("nombre"), A("puesto")]),
                E("TERAPEUTA", []),
                E("TRATAMIENTO", [K("cód_tratamiento"), A("nombre")])],
               [R("tiene", [("PLANTA", "(1,1)", None), ("HABITACIÓN", "(1,N)", None)], ident=True),
                R("se asigna a", [("ALOJADO", "(0,N)", None), ("HABITACIÓN", "(1,N)", None)], [KP("fecha_asignación")]),
                R("coordina", [("TERAPEUTA", "(0,1)", "senior"), ("TERAPEUTA", "(0,N)", "junior")]),
                R("presta", [("CLIENTE", "(0,N)", None), ("TERAPEUTA", "(0,N)", None), ("TRATAMIENTO", "(0,N)", None)],
                  [KP("fecha"), KP("hora"), A("duración_min"), A("observaciones")])],
               [ISA("CLIENTE", ["ALOJADO", "AMBULANTE"], "d", True),
                ISA("HABITACIÓN", ["SUITE", "ESTÁNDAR"], "d", True),
                ISA("EMPLEADO", ["TERAPEUTA"], "d", False)]))

ej(n=23, titulo="Red eléctrica: centrales, nodos y suministro", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario + restricciones",
   objetivo="Resolver una especialización con tres subclases, una entidad débil, una reflexiva N:M con atributos y una ternaria.",
   contexto="El Ministerio quiere un sistema para controlar la producción, el transporte y el suministro de electricidad.",
   enun=["Las **centrales** se identifican por un código; se guarda también el nombre (único), la producción media y la fecha de entrada en funcionamiento. Son obligatoriamente **hidroeléctricas** (río, embalse y volumen útil), **térmicas** (combustible y emisiones) o **renovables** (número de generadores y superficie de captación).",
         "Cada central mantiene un registro de **partes de mantenimiento**, identificados por un número de incidencia dentro de la central (1, 2, 3…), con la fecha de la revisión, la empresa mantenedora y el coste.",
         "La transmisión se realiza a través de **nodos** de la red (código y nombre) unidos entre sí por **líneas** de transmisión, con su capacidad en kV y la distancia en km.",
         "El suministro mayorista es un acuerdo conjunto entre la **central**, la **comercializadora** (CIF y nombre) y la **zona** de distribución (código y nombre), con los MWh contratados, la tarifa y la fecha del contrato."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica la jerarquía de centrales y explica por qué el atributo común `producción_media` va en la superclase.",
           "Modela el suministro como ternaria. ¿Qué atributo permite repetir el acuerdo entre las mismas tres entidades?",
           "Escribe tres restricciones: el nombre único, la capacidad positiva y el parte con fecha posterior a la puesta en marcha."],
   comp=["La jerarquía es **total y disyunta** con tres subclases.",
         "*Línea* es una reflexiva N:M con dos atributos.",
         "`PARTE` es débil de `CENTRAL`.",
         "*Suministro* es una ternaria."],
   err=["Crear una entidad `LÍNEA` aparte sin necesidad: es una relación entre nodos con atributos.",
        "Meter río y embalse en `CENTRAL`: solo tienen sentido en las hidroeléctricas."],
   amp="Las centrales renovables se dividen a su vez en **solares** y **eólicas** con atributos propios. Añade una segunda jerarquía bajo `RENOVABLE` y razona cómo se clasificaría.",
   dec=["`CENTRAL` se especializa en tres subclases con atributos propios.",
        "`PARTE` depende de `CENTRAL`: (código de central, nº de incidencia).",
        "*Línea* es N:M reflexiva sobre `NODO` con `capacidad_kv` y `distancia_km`; *suministro* es ternaria."],
   sup=["Toda central pertenece a una de las tres clases.",
        "Un nodo puede no tener líneas aún.",
        "Una línea une dos nodos distintos (restricción textual).",
        "La capacidad y la distancia son positivas (restricción de dominio)."],
   model=Model("Red eléctrica: centrales, nodos y suministro",
               "CENTRAL se especializa en hidroeléctrica, térmica y renovable y tiene PARTE (débil). NODO se une a NODO mediante líneas. CENTRAL, COMERCIALIZADORA y ZONA se relacionan en suministro.",
               [E("CENTRAL", [K("cód_central"), A("nombre"), A("producción_media"), A("fecha_puesta_en_marcha")]),
                E("HIDROELÉCTRICA", [A("río"), A("embalse"), A("volumen_útil")]),
                E("TÉRMICA", [A("combustible"), A("emisiones")]),
                E("RENOVABLE", [A("nº_generadores"), A("superficie")]),
                E("PARTE", [KP("nº_incidencia"), A("fecha"), A("empresa"), A("coste")], weak=True),
                E("NODO", [K("cód_nodo"), A("nombre")]),
                E("COMERCIALIZADORA", [K("cif"), A("nombre")]),
                E("ZONA", [K("cód_zona"), A("nombre")])],
               [R("registra", [("CENTRAL", "(1,1)", None), ("PARTE", "(0,N)", None)], ident=True),
                R("línea", [("NODO", "(0,N)", "extremo A"), ("NODO", "(0,N)", "extremo B")], [A("capacidad_kv"), A("distancia_km")]),
                R("suministro", [("CENTRAL", "(0,N)", None), ("COMERCIALIZADORA", "(0,N)", None), ("ZONA", "(0,N)", None)],
                  [KP("fecha_contrato"), A("MWh"), A("tarifa")])],
               [ISA("CENTRAL", ["HIDROELÉCTRICA", "TÉRMICA", "RENOVABLE"], "d", True)]))

ej(n=24, titulo="Festival de música: ediciones, escenarios y actuaciones", nivel=3, dur="2 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario + restricciones",
   objetivo="Modelar una **cadena de entidades débiles** (festival → edición → escenario), una especialización y una actuación repetible.",
   contexto="Un promotor organiza un festival que se repite cada año y quiere guardar todo su histórico.",
   enun=["Un **festival** (código, nombre y ciudad) se celebra cada año. Cada **edición** se identifica por el año dentro del festival y tiene fecha de inicio, fecha de fin y aforo.",
         "Cada edición monta varios **escenarios**, identificados por su nombre dentro de la edición (*Principal*, *Electrónica*…), con su capacidad.",
         "Los **artistas** (código, nombre artístico y país) son **solistas** (instrumento) o **grupos** (número de componentes). Cada artista **actúa** en escenarios; de cada actuación se guarda la fecha, la hora de inicio, la duración y el caché. Un artista puede actuar varias veces en el mismo escenario.",
         "Los **asistentes** (DNI, nombre y correo) compran **entradas** para una edición. Cada entrada se numera dentro de la edición y tiene un tipo (*general*, *vip* o *abono*) y un precio. Una entrada la compra un único asistente, aunque puede estar sin vender."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Escribe el identificador completo de `ESCENARIO` y explica por qué necesita tres componentes.",
           "Razona por qué la *actuación* es una relación con atributos y qué atributos forman parte de su identificación.",
           "Escribe tres restricciones: solapes de actuaciones en el mismo escenario, fechas dentro de la edición y entradas vendidas frente al aforo."],
   comp=["`EDICIÓN` es débil de `FESTIVAL` y `ESCENARIO` es débil de `EDICIÓN`.",
         "`ENTRADA` es débil de `EDICIÓN`.",
         "La especialización de artistas es **total y disyunta**.",
         "*Actúa* tiene la fecha y la hora de inicio como discriminador."],
   err=["Identificar el escenario solo por su nombre: «Principal» existe en todas las ediciones.",
        "Relacionar al artista con la edición y no con el escenario: pierdes dónde y cuándo actúa."],
   amp="Los festivales tienen **patrocinadores** que aportan un importe por edición. Añade esta relación y decide con qué entidad se establece. ¿Qué atributos lleva?",
   dec=["Cadena de dependencias: `FESTIVAL` → `EDICIÓN` → `ESCENARIO`. El identificador del escenario es (festival, año, nombre).",
        "*Actúa* es N:M repetible: fecha y hora de inicio forman parte de su identificación.",
        "`ENTRADA` depende de la edición y se asigna opcionalmente a un asistente."],
   sup=["Un festival tiene al menos una edición.",
        "Una entrada puede estar sin vender: (0,1) asistente.",
        "Las actuaciones de un escenario no se solapan (restricción textual).",
        "Las fechas de las actuaciones están dentro de las fechas de la edición (restricción textual)."],
   model=Model("Festival de música: ediciones, escenarios y actuaciones",
               "FESTIVAL tiene EDICIÓN (débil). EDICIÓN monta ESCENARIO (débil) y emite ENTRADA (débil). ARTISTA, solista o grupo, actúa en ESCENARIO. ASISTENTE compra ENTRADA.",
               [E("FESTIVAL", [K("cód_festival"), A("nombre"), A("ciudad")]),
                E("EDICIÓN", [KP("año"), A("fecha_inicio"), A("fecha_fin"), A("aforo")], weak=True),
                E("ESCENARIO", [KP("nombre"), A("capacidad")], weak=True),
                E("ARTISTA", [K("cód_artista"), A("nombre_artístico"), A("país")]),
                E("SOLISTA", [A("instrumento")]), E("GRUPO", [A("nº_componentes")]),
                E("ASISTENTE", [K("dni"), A("nombre"), A("email")]),
                E("ENTRADA", [KP("nº_entrada"), A("tipo"), A("precio")], weak=True)],
               [R("celebra", [("FESTIVAL", "(1,1)", None), ("EDICIÓN", "(1,N)", None)], ident=True),
                R("monta", [("EDICIÓN", "(1,1)", None), ("ESCENARIO", "(1,N)", None)], ident=True),
                R("emite", [("EDICIÓN", "(1,1)", None), ("ENTRADA", "(0,N)", None)], ident=True),
                R("actúa", [("ARTISTA", "(0,N)", None), ("ESCENARIO", "(0,N)", None)],
                  [KP("fecha"), KP("hora_inicio"), A("duración_min"), A("caché")]),
                R("compra", [("ASISTENTE", "(0,1)", None), ("ENTRADA", "(0,N)", None)])],
               [ISA("ARTISTA", ["SOLISTA", "GRUPO"], "d", True)]))

ej(n=25, titulo="Muestra gastronómica: provincias, platos, restaurantes y vinos", nivel=3, dur="2-3 sesiones",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + diccionario + restricciones",
   objetivo="Resolver un caso de integración con tres entidades débiles dependientes de la misma propietaria, una especialización y tres relaciones N:M, y justificar cada decisión.",
   contexto="Se organiza una muestra de platos típicos de España con información de las localidades, los restaurantes, las visitas y los vinos que los acompañan.",
   enun=["De las **provincias** se conoce el nombre, la extensión y la capital. De las **localidades** (nombre, tamaño y habitantes), dos localidades de provincias distintas pueden llamarse igual.",
         "De los **platos típicos** se guarda el nombre, los ingredientes básicos (varios) y la forma de preparación. Un plato puede ser típico de varias localidades y una localidad puede conservar varios platos típicos. Para cada pareja plato-localidad se anotan las **variaciones locales** de la receta.",
         "En las localidades hay **restaurantes** (nombre, dirección, teléfono, precio del menú del día y capacidad). Los nombres pueden repetirse entre localidades, nunca dentro de una. Cada restaurante debe estar especializado en **al menos uno** de los platos típicos.",
         "En cada localidad se planifican **visitas guiadas** (nombre del lugar, único por localidad). Las visitas **culturales** tienen horario; las **industriales** (fábricas de embutidos, sidra…) tienen persona de contacto y teléfono.",
         "Las **bodegas** patrocinadoras (CIF, nombre del director, dirección de la sede y teléfono) ofrecen **vinos** (código, cosecha, grado, color y textura). Un grupo de expertos aconseja qué vinos servir con cada plato."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Identifica las tres entidades débiles y escribe sus identificadores completos. Explica por qué `LOCALIDAD` es débil de `PROVINCIA`.",
           "Clasifica la jerarquía de visitas y justifica la clasificación con una frase del enunciado.",
           "Elabora el **diccionario de datos** de `LOCALIDAD`, `RESTAURANTE` y de la relación plato-localidad.",
           "Escribe cuatro restricciones y propón qué lista de tablas saldría al pasar al modelo relacional (adelanto de la UD03)."],
   comp=["`LOCALIDAD`, `RESTAURANTE` y `VISITA` son entidades débiles.",
         "*Es típico de* es una N:M con el atributo `variación_local`.",
         "La jerarquía de visitas es **total y disyunta**.",
         "`ingredientes_básicos` es multivaluado."],
   err=["Identificar la localidad solo por su nombre: Villanueva existe en muchas provincias.",
        "Relacionar el restaurante con el plato sin exigir el mínimo 1: «debe estar especializado en al menos uno»."],
   amp="Los expertos aconsejan un vino **distinto según la temporada** (invierno o verano). ¿Cómo cambia la relación entre `PLATO` y `VINO`? ¿Se convierte en ternaria?",
   dec=["`PROVINCIA` es propietaria de `LOCALIDAD` (identificador: provincia + nombre) y `LOCALIDAD`, de `RESTAURANTE` y `VISITA`.",
        "*Es típico de* (N:M con `variación_local`), *especializado en* (N:M con mínimo 1 para el restaurante) y *aconseja* (N:M) son tres relaciones distintas.",
        "Visitas: especialización total y disyunta en culturales (horario) e industriales (contacto y teléfono)."],
   sup=["Toda localidad pertenece a una provincia.",
        "Un restaurante está especializado en al menos un plato: (1,N).",
        "El plato en que se especializa un restaurante debe ser típico de su localidad (restricción textual).",
        "Cada vino pertenece a una única bodega."],
   model=Model("Muestra gastronómica: provincias, platos, restaurantes y vinos",
               "PROVINCIA tiene LOCALIDAD (débil), que ubica RESTAURANTE (débil) y ofrece VISITA (débil), cultural o industrial. PLATO es típico de LOCALIDAD, RESTAURANTE se especializa en PLATO. BODEGA ofrece VINO y PLATO se aconseja con VINO.",
               [E("PROVINCIA", [K("nombre"), A("extensión"), A("capital")]),
                E("LOCALIDAD", [KP("nombre"), A("tamaño"), A("habitantes")], weak=True),
                E("PLATO", [K("nombre"), MV("ingredientes"), A("preparación")]),
                E("RESTAURANTE", [KP("nombre"), A("dirección"), A("teléfono"), A("precio_menú"), A("capacidad")], weak=True),
                E("VISITA", [KP("lugar")], weak=True),
                E("CULTURAL", [A("horario")]),
                E("INDUSTRIAL", [A("contacto"), A("teléfono")]),
                E("BODEGA", [K("cif"), A("director"), A("dir_sede"), A("teléfono")]),
                E("VINO", [K("cód_vino"), A("cosecha"), A("grado"), A("color"), A("textura")])],
               [R("pertenece a", [("PROVINCIA", "(1,1)", None), ("LOCALIDAD", "(1,N)", None)], ident=True),
                R("es típico de", [("PLATO", "(0,N)", None), ("LOCALIDAD", "(1,N)", None)], [A("variación_local")]),
                R("ubica", [("LOCALIDAD", "(1,1)", None), ("RESTAURANTE", "(0,N)", None)], ident=True),
                R("especializado en", [("RESTAURANTE", "(0,N)", None), ("PLATO", "(1,N)", None)]),
                R("ofrece visita", [("LOCALIDAD", "(1,1)", None), ("VISITA", "(0,N)", None)], ident=True),
                R("ofrece", [("BODEGA", "(1,1)", None), ("VINO", "(1,N)", None)]),
                R("aconseja", [("PLATO", "(0,N)", None), ("VINO", "(0,N)", None)])],
               [ISA("VISITA", ["CULTURAL", "INDUSTRIAL"], "d", True)]))
