# -*- coding: utf-8 -*-
"""Banco de ejercicios UD02 · bloques 1 y 2 (ejercicios 1-12)."""
from chen_eer import *

EJS = []


def ej(**kw):
    EJS.append(kw)


# ============================================================ BLOQUE 1
ej(n=1, titulo="Ventas: clientes, productos y proveedores", nivel=1, dur="1 sesión",
   ra="RA6: a, d, e", entrega="Diagrama EER + supuestos",
   objetivo="Identificar entidades, atributos e identificadores y distinguir una relación 1:N de una N:M.",
   contexto="Una pequeña empresa de distribución quiere informatizar sus ventas y sus compras a proveedores.",
   enun=["Una empresa comercializa productos a clientes finales y se abastece mediante proveedores externos.",
         "De cada **cliente** se conocen el DNI, el nombre, los apellidos, la dirección y la fecha de nacimiento. Un cliente puede comprar varios productos y un mismo producto puede ser adquirido por diferentes clientes.",
         "De cada **producto** se almacena un código identificativo, el nombre y el precio unitario.",
         "Los productos los suministran **proveedores**. Cada producto lo suministra un único proveedor (exclusivo), mientras que un proveedor puede suministrar varios productos. De cada proveedor se desea conocer el NIF, el nombre y la dirección."],
   tareas=["Dibuja el diagrama EER en notación de Chen: entidades, atributos, claves y relaciones con su cardinalidad (mín, máx).",
           "Explica con una frase por qué *comprar* es N:M y *suministrar* es 1:N.",
           "Anota los supuestos sobre las cardinalidades **mínimas**, que el enunciado no indica."],
   comp=["Hay tres entidades y dos relaciones, cada una con su rombo.",
         "El máximo es 1 junto a `PROVEEDOR` (cada producto tiene un único proveedor) y N junto a `PRODUCTO`.",
         "Cada entidad tiene su identificador subrayado.",
         "Has escrito al menos dos supuestos."],
   err=["Dibujar *compra* como 1:N porque «un cliente compra productos». Formula siempre la pregunta en **los dos sentidos**.",
        "Poner el NIF del proveedor como atributo de `PRODUCTO`. Repetirías los datos del proveedor en cada producto."],
   amp="La empresa quiere guardar la **fecha** y la **cantidad** de cada compra. ¿Dónde colocas esos atributos? ¿Qué problema aparece si un cliente compra el mismo producto en dos días distintos?",
   dec=["*Compra* es **N:M**: un cliente compra muchos productos y un producto lo compran muchos clientes.",
        "*Suministra* es **1:N**: el máximo es 1 en el lado del proveedor. Por eso no hace falta una tabla intermedia cuando se pase al modelo relacional (UD03).",
        "Los atributos de cada entidad son los del enunciado; el DNI, el código y el NIF identifican."],
   sup=["Un cliente puede estar registrado sin haber comprado todavía: (0,N).",
        "Todo producto tiene proveedor: (1,1).",
        "Un proveedor puede estar dado de alta sin productos: (0,N).",
        "El DNI, el código del producto y el NIF no se repiten."],
   model=Model("Ventas, clientes, productos y proveedores",
               "CLIENTE compra PRODUCTO (N:M). PROVEEDOR suministra PRODUCTO (1:N).",
               [E("CLIENTE", [K("dni"), A("nombre"), A("apellidos"), A("dirección"), A("fecha_nacimiento")]),
                E("PRODUCTO", [K("código"), A("nombre"), A("precio_unitario")]),
                E("PROVEEDOR", [K("nif"), A("nombre"), A("dirección")])],
               [R("compra", [("CLIENTE", "(0,N)", None), ("PRODUCTO", "(0,N)", None)]),
                R("suministra", [("PROVEEDOR", "(1,1)", None), ("PRODUCTO", "(0,N)", None)])]))

ej(n=2, titulo="Naviera: capitanes, contenedores, puertos y barcos", nivel=1, dur="1 sesión",
   ra="RA6: a, d, e", entrega="Diagrama EER + supuestos",
   objetivo="Encadenar varias relaciones 1:N y modelar un histórico mediante una relación N:M con atributos propios.",
   contexto="Una naviera internacional necesita gestionar su flota y las mercancías que transporta.",
   enun=["De los **capitanes** se quiere guardar el DNI, el nombre, el teléfono, la dirección, el salario y la población de residencia. Un capitán transporta muchos contenedores y cada contenedor lo transporta un único capitán.",
         "De los **contenedores** interesa conocer el código, una descripción, la dirección del remitente y la dirección del destinatario. Cada contenedor tiene como destino un único **puerto**, pero a un puerto pueden llegar muchos contenedores. De los puertos se guarda el código y el nombre.",
         "De los **barcos** se conoce la matrícula, el nombre, la potencia del motor y el astillero. Un capitán puede gobernar distintos barcos en fechas diferentes (se registra la fecha de inicio y la de fin) y un barco puede ser gobernado por varios capitanes a lo largo del tiempo."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Indica qué relaciones son 1:N y cuál es N:M, y justifícalo con las preguntas en los dos sentidos.",
           "Decide dónde van `fecha_inicio` y `fecha_fin` y explica por qué no pueden ser atributos de `CAPITÁN` ni de `BARCO`.",
           "Anota los supuestos."],
   comp=["Hay cuatro entidades y tres relaciones.",
         "Las fechas están en la relación *gobierna*, no en las entidades.",
         "Has pensado qué ocurre si el **mismo** capitán gobierna el **mismo** barco en dos periodos distintos.",
         "`dirección_remitente` y `dirección_destinatario` están en `CONTENEDOR`."],
   err=["Poner `fecha_inicio` en `BARCO`: un barco tiene muchos capitanes y solo podría guardar una fecha.",
        "Relacionar directamente `CAPITÁN` con `PUERTO`. El puerto se deduce del contenedor."],
   pista=("Pista: histórico de una relación N:M",
          "Si el mismo capitán puede volver a gobernar el mismo barco, la pareja (capitán, barco) **no basta** para distinguir cada periodo. La `fecha_inicio` debe formar parte de la identificación. En el diagrama se marca con subrayado discontinuo."),
   amp="La naviera quiere saber en qué **barco** viaja cada contenedor. ¿Cómo se modifica el modelo? ¿Sigue siendo necesaria la relación entre capitán y contenedor?",
   dec=["*Transporta* y *llega a* son 1:N en cadena: capitán → contenedor → puerto.",
        "*Gobierna* es N:M y lleva `fecha_inicio` y `fecha_fin`. `fecha_inicio` se marca como discriminador (subrayado discontinuo) porque permite repetir la pareja capitán-barco en periodos distintos.",
        "El puerto de destino es una entidad: tiene datos propios (código y nombre) y varios contenedores comparten el mismo puerto."],
   sup=["Todo contenedor tiene capitán y puerto de destino: (1,1).",
        "Un capitán puede no haber transportado aún ningún contenedor.",
        "`fecha_fin` está vacía mientras el capitán sigue al mando del barco.",
        "Un capitán no gobierna dos barcos a la vez (restricción que el diagrama no recoge)."],
   model=Model("Naviera: capitanes, contenedores, puertos y barcos",
               "CAPITÁN transporta CONTENEDOR (1:N). CONTENEDOR llega a PUERTO (N:1). CAPITÁN gobierna BARCO (N:M con fechas).",
               [E("CAPITÁN", [K("dni"), A("nombre"), A("teléfono"), A("dirección"), A("salario"), A("población")]),
                E("CONTENEDOR", [K("cód_contenedor"), A("descripción"), A("dir_remitente"), A("dir_destinatario")]),
                E("PUERTO", [K("cód_puerto"), A("nombre")]),
                E("BARCO", [K("matrícula"), A("nombre"), A("potencia_motor"), A("astillero")])],
               [R("transporta", [("CAPITÁN", "(1,1)", None), ("CONTENEDOR", "(0,N)", None)]),
                R("llega a", [("CONTENEDOR", "(0,N)", None), ("PUERTO", "(1,1)", None)]),
                R("gobierna", [("CAPITÁN", "(0,N)", None), ("BARCO", "(0,N)", None)],
                  [KP("fecha_inicio"), A("fecha_fin")])]))

ej(n=3, titulo="Multas de tráfico municipales", nivel=1, dur="1 sesión",
   ra="RA6: a, d, e", entrega="Diagrama EER + justificación",
   objetivo="Decidir si un hecho repetible (la multa) se modela como relación con atributos o como entidad.",
   contexto="Un ayuntamiento quiere gestionar las infracciones de tráfico y las multas asociadas.",
   enun=["De cada **vehículo** se registra la matrícula, el tipo, la marca y el modelo. Un vehículo pertenece a un **propietario** registrado. De los propietarios interesa guardar el DNI, el nombre, los apellidos y la dirección. Un propietario puede tener varios vehículos.",
         "Existe un catálogo de **infracciones** con su código, una descripción y la cuantía a pagar.",
         "Cuando un vehículo comete una infracción se genera la **multa** correspondiente, con la fecha de la sanción y la fecha de pago. Un mismo vehículo puede recibir varias multas a lo largo del tiempo y una infracción del catálogo puede cometerse muchas veces por distintos vehículos."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "¿La multa es una **relación** o una **entidad**? Razona las dos opciones y quédate con una.",
           "Un vehículo puede cometer **la misma infracción** dos veces. ¿Qué atributo tiene que formar parte de la identificación de la multa?",
           "Anota los supuestos."],
   comp=["Existen tres entidades: `PROPIETARIO`, `VEHÍCULO` e `INFRACCIÓN`.",
         "`cuantía` está en `INFRACCIÓN`, no en la multa (es del catálogo).",
         "Has resuelto la repetición de la misma infracción en el mismo vehículo.",
         "`fecha_pago` puede estar vacía y lo has anotado."],
   err=["Guardar la cuantía en la multa **y** en la infracción: si cambia el catálogo, ¿qué cuantía es la correcta?",
        "Modelar la multa como atributo de `VEHÍCULO`. Un vehículo tiene muchas multas."],
   amp="La multa puede **recurrirse** varias veces (fecha del recurso y resolución). ¿Sigue siendo adecuada una relación con atributos? Razona por qué la multa pasaría a ser entidad.",
   dec=["*Posee* es 1:N: el máximo es 1 en el lado del propietario.",
        "*Se sanciona con* es una N:M entre `VEHÍCULO` e `INFRACCIÓN` con `fecha_sanción` (discriminador) y `fecha_pago`. Es la opción más compacta si la multa no tiene vida propia.",
        "Alternativa válida: `MULTA` como entidad con un número de multa y dos relaciones 1:N. Es preferible si la multa se recurre, se notifica o se fracciona (ver ampliación)."],
   sup=["Un propietario puede estar registrado sin vehículos.",
        "Un vehículo tiene siempre un propietario.",
        "Un vehículo no recibe dos multas por la misma infracción en la misma fecha.",
        "`fecha_pago` está vacía mientras la multa está pendiente."],
   model=Model("Multas de tráfico municipales",
               "PROPIETARIO posee VEHÍCULO (1:N). VEHÍCULO se sanciona con INFRACCIÓN (N:M con fecha de sanción y fecha de pago).",
               [E("PROPIETARIO", [K("dni"), A("nombre"), A("apellidos"), A("dirección")]),
                E("VEHÍCULO", [K("matrícula"), A("tipo"), A("marca"), A("modelo")]),
                E("INFRACCIÓN", [K("cód_infracción"), A("descripción"), A("cuantía")])],
               [R("posee", [("PROPIETARIO", "(1,1)", None), ("VEHÍCULO", "(0,N)", None)]),
                R("se sanciona con", [("VEHÍCULO", "(0,N)", None), ("INFRACCIÓN", "(0,N)", None)],
                  [KP("fecha_sanción"), A("fecha_pago")])]))

ej(n=4, titulo="Parentesco y filiación", nivel=1, dur="1 sesión",
   ra="RA6: d, h", entrega="Diagrama EER + análisis del enunciado",
   objetivo="Modelar una relación **reflexiva** y detectar una cardinalidad mínima imposible.",
   contexto="Un registro genealógico quiere guardar quién es progenitor de quién.",
   enun=["Se desea diseñar una base de datos que registre las relaciones de parentesco entre **personas**. De cada persona se conocen el DNI, el nombre, la dirección y el teléfono.",
         "Una persona puede ser progenitora (padre o madre) de varios hijos o hijas, o de ninguno. Toda persona registrada en el sistema debe tener registrada obligatoriamente su filiación directa con su progenitor o progenitora."],
   tareas=["Dibuja el diagrama EER con una **relación reflexiva** y los **roles** (progenitor, hijo).",
           "Escribe las cardinalidades (mín, máx) de cada rol según el enunciado y razona si es posible mantenerlas en una base de datos real.",
           "Propón una cardinalidad mínima que sí sea viable y justifica el cambio.",
           "Anota los supuestos."],
   comp=["Solo hay una entidad y la relación sale y vuelve a ella.",
         "Los dos extremos de la relación tienen **rol**.",
         "Has detectado el problema de las personas sin ascendientes registrados.",
         "El máximo del rol *progenitor* es 1."],
   err=["Crear dos entidades `PADRE` e `HIJO`. Ambos son `PERSONA` y una persona puede ser a la vez padre e hijo.",
        "Mantener (1,1) en el rol de progenitor: obligaría a que cada persona tuviera un progenitor registrado, y este otro, y así sin fin."],
   pista=("Pista: ¿quién es el primer antepasado?",
          "Si todas las personas deben tener progenitor registrado y la base de datos es finita, la cadena de ascendientes tendría que cerrarse en un ciclo. Esto es imposible. El mínimo del rol *progenitor* tiene que ser 0."),
   amp="Se quiere registrar **los dos** progenitores de cada persona. ¿Cambia la cardinalidad? ¿La relación sigue siendo 1:N o pasa a ser N:M con máximo 2 en uno de los roles?",
   dec=["*Es progenitor de* es una relación reflexiva 1:N: una persona tiene como mucho un progenitor registrado y puede tener muchos hijos.",
        "El enunciado pide (1,1) en el rol de progenitor, pero eso es insostenible: se corrige a **(0,1)** y se documenta como restricción de negocio (RA6.h).",
        "Los roles distinguen los dos extremos de la misma entidad."],
   sup=["Las personas fundadoras del árbol no tienen progenitor registrado.",
        "Una persona no puede ser progenitora de sí misma ni de sus ascendientes (restricción que el diagrama no recoge).",
        "La relación se registra solo con un progenitor directo."],
   model=Model("Parentesco y filiación",
               "PERSONA es progenitor de PERSONA: relación reflexiva 1:N con los roles progenitor e hijo.",
               [E("PERSONA", [K("dni"), A("nombre"), A("dirección"), A("teléfono")])],
               [R("es progenitor de", [("PERSONA", "(0,1)", "progenitor"), ("PERSONA", "(0,N)", "hijo")])]))

# ============================================================ BLOQUE 2
ej(n=5, titulo="Instituto: módulos, matrículas, delegados y casilleros", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones textuales",
   objetivo="Distinguir relaciones 1:1, dos relaciones distintas entre las mismas entidades y una N:M reflexiva.",
   contexto="Un instituto de Educación Secundaria y Formación Profesional diseña su base de datos de docencia.",
   enun=["De los **profesores** se guarda el DNI, el nombre, la dirección y el teléfono. Los profesores imparten **módulos**, cada uno con un código y un nombre. Un profesor puede impartir varios módulos, pero cada módulo lo imparte un único profesor.",
         "Algunos módulos tienen como **prerrequisito** haber cursado otros. Un módulo puede exigir varios módulos previos y, a su vez, ser requisito de otros.",
         "De cada **alumno** se almacena el número de expediente, el nombre, los apellidos y la fecha de nacimiento. Un alumno se matricula en uno o varios módulos y se registra la fecha de matriculación.",
         "Cada alumno pertenece a un **grupo**, que tiene un código y un curso. En cada grupo se elige a un alumno como **delegado**.",
         "Los alumnos que lo soliciten pueden disponer de un **casillero** (número y tamaño en metros). Un casillero pertenece a un único alumno y un alumno tiene como máximo un casillero."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Entre `ALUMNO` y `GRUPO` hay **dos** relaciones. Explica por qué no pueden fusionarse en una sola.",
           "Calcula las cardinalidades de la relación con el casillero y razona por qué el mínimo no es el mismo en los dos lados.",
           "Escribe al menos **dos restricciones** que el diagrama no puede expresar (por ejemplo, sobre el delegado)."],
   comp=["*Prerrequisito* es una N:M reflexiva con dos roles.",
         "*Delegado* y *pertenece* son relaciones distintas con cardinalidades distintas.",
         "La relación alumno–casillero es 1:1 con mínimo 0 en un lado y 1 en el otro.",
         "`fecha_matriculación` está en la relación *se matricula*."],
   err=["Usar un único atributo `es_delegado` en `ALUMNO`: no garantiza que haya exactamente un delegado por grupo.",
        "Dibujar *prerrequisito* como 1:N. Un módulo puede tener varios previos y ser previo de varios."],
   amp="Algunos alumnos repiten curso y se matriculan **dos veces** en el mismo módulo en cursos académicos distintos. ¿Cómo cambia la relación *se matricula*?",
   dec=["*Imparte* es 1:N; *se matricula* es N:M con atributo; *prerrequisito* es N:M reflexiva.",
        "*Pertenece* (1:N) y *delegado* (1:1) son hechos distintos entre `ALUMNO` y `GRUPO`: la primera la tiene todo alumno; la segunda solo un alumno por grupo.",
        "En *casillero* el mínimo es 0 en el lado del alumno (no todos lo piden) y 1 en el del casillero (siempre tiene dueño)."],
   sup=["Todo módulo tiene profesor asignado: (1,1).",
        "Un grupo siempre tiene delegado: (1,1) en el lado del alumno.",
        "El delegado debe pertenecer al grupo que representa (restricción textual).",
        "Un módulo no puede ser prerrequisito de sí mismo ni formar ciclos (restricción textual)."],
   model=Model("Instituto: módulos, matrículas, delegados y casilleros",
               "PROFESOR imparte MÓDULO; MÓDULO es prerrequisito de MÓDULO; ALUMNO se matricula en MÓDULO; ALUMNO pertenece a GRUPO y es delegado de GRUPO; ALUMNO tiene CASILLERO.",
               [E("PROFESOR", [K("dni"), A("nombre"), A("dirección"), A("teléfono")]),
                E("MÓDULO", [K("cód_módulo"), A("nombre")]),
                E("ALUMNO", [K("nº_expediente"), A("nombre"), A("apellidos"), A("fecha_nacimiento")]),
                E("GRUPO", [K("cód_grupo"), A("curso")]),
                E("CASILLERO", [K("nº_casillero"), A("tamaño_m")])],
               [R("imparte", [("PROFESOR", "(1,1)", None), ("MÓDULO", "(0,N)", None)]),
                R("prerrequisito", [("MÓDULO", "(0,N)", "previo"), ("MÓDULO", "(0,N)", "posterior")]),
                R("se matricula", [("ALUMNO", "(0,N)", None), ("MÓDULO", "(1,N)", None)], [A("fecha_matrícula")]),
                R("pertenece", [("GRUPO", "(1,1)", None), ("ALUMNO", "(0,N)", None)]),
                R("delegado", [("ALUMNO", "(1,1)", None), ("GRUPO", "(0,1)", None)]),
                R("usa", [("ALUMNO", "(1,1)", None), ("CASILLERO", "(0,1)", None)])]))

ej(n=6, titulo="Hospital: pacientes, ingresos y médicos", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e", entrega="Diagrama EER + supuestos",
   objetivo="Reconocer una **entidad débil** y su identificación por dependencia con un atributo compuesto.",
   contexto="Una clínica quiere controlar los ingresos de sus pacientes y los médicos que los atienden.",
   enun=["De cada **paciente** se guarda el código, el nombre, los apellidos, la dirección (calle, población, provincia y código postal), el teléfono y la fecha de nacimiento.",
         "De cada **médico** se conserva el código, el nombre, los apellidos, el teléfono y la especialidad.",
         "Se controlan los **ingresos** de cada paciente. Cada ingreso se identifica con un número que empieza en 1 para cada paciente, e incluye el número de habitación, la cama y la fecha de ingreso. Un paciente puede ingresar varias veces y un ingreso no puede existir sin el paciente al que corresponde.",
         "Cada ingreso lo atiende un único médico responsable, aunque un médico puede atender muchos ingresos de pacientes distintos."],
   tareas=["Dibuja el diagrama EER con la entidad débil, la relación identificadora y el atributo compuesto.",
           "Escribe el **identificador completo** de `INGRESO` y explica por qué el número de ingreso no basta.",
           "Anota los supuestos.",
           "Escribe una restricción que el diagrama no pueda expresar."],
   comp=["`INGRESO` es una entidad débil (doble rectángulo) con relación identificadora (doble rombo).",
         "El número de ingreso es un discriminador (subrayado discontinuo).",
         "`dirección` es un atributo compuesto.",
         "*Atiende* es 1:N entre `MÉDICO` e `INGRESO`."],
   err=["Usar el número de ingreso como clave: el ingreso 1 lo tienen todos los pacientes.",
        "Relacionar `MÉDICO` con `PACIENTE`. Quien atiende cada ingreso puede cambiar de uno a otro."],
   amp="Un ingreso puede ser atendido por **varios médicos** que se turnan. ¿Cómo cambia *atiende*? ¿Qué atributo habría que guardar en la relación?",
   dec=["`INGRESO` depende de `PACIENTE`: su identificador es (código de paciente, número de ingreso).",
        "*Realiza* es identificadora, 1:N; el paciente tiene (1,1) en el lado del ingreso y el ingreso (0,N) en el del paciente.",
        "*Atiende* conecta `MÉDICO` con `INGRESO` y es 1:N."],
   sup=["Un paciente puede estar registrado sin ingresos (pre-registro).",
        "Todo ingreso tiene médico responsable.",
        "La cama y la habitación se guardan como texto simple; no hay entidad `HABITACIÓN`.",
        "No pueden existir dos ingresos activos en la misma cama (restricción textual)."],
   model=Model("Hospital: pacientes, ingresos y médicos",
               "PACIENTE realiza INGRESO (relación identificadora, INGRESO es débil). MÉDICO atiende INGRESO (1:N).",
               [E("PACIENTE", [K("cód_paciente"), A("nombre"), A("apellidos"),
                               C("dirección", "calle", "población", "provincia", "cód_postal"),
                               A("teléfono"), A("fecha_nacimiento")]),
                E("MÉDICO", [K("cód_médico"), A("nombre"), A("apellidos"), A("teléfono"), A("especialidad")]),
                E("INGRESO", [KP("nº_ingreso"), A("habitación"), A("cama"), A("fecha_ingreso")], weak=True)],
               [R("realiza", [("PACIENTE", "(1,1)", None), ("INGRESO", "(0,N)", None)], ident=True),
                R("atiende", [("MÉDICO", "(1,1)", None), ("INGRESO", "(0,N)", None)])]))

ej(n=7, titulo="Tienda online: pedidos, líneas y categorías", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + atributos derivados",
   objetivo="Combinar entidad débil, relación reflexiva, atributos multivaluados, compuestos y derivados en un caso de comercio electrónico.",
   contexto="Una tienda de ropa online quiere sustituir su hoja de cálculo por una base de datos.",
   enun=["De cada **cliente** se guarda el correo electrónico (único), el nombre, los apellidos, una dirección de facturación (calle, código postal y ciudad) y uno o varios teléfonos.",
         "Los **productos** tienen un código, un nombre, una descripción, un precio y las unidades en stock. Cada producto pertenece a una **categoría**. Las categorías se organizan en árbol: una categoría puede ser subcategoría de otra (*Ropa → Camisetas*).",
         "Los clientes realizan **pedidos**. De cada pedido se guarda el número, la fecha, el estado y el importe total, que se calcula a partir de las líneas. Un pedido contiene una o varias **líneas** numeradas dentro del pedido (1, 2, 3…). Cada línea corresponde a un producto y guarda la cantidad y el **precio unitario en el momento de la compra**."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Clasifica cada atributo: simple, compuesto, multivaluado o derivado.",
           "Explica por qué `precio_unitario` está en la línea y no solo en `PRODUCTO`.",
           "Escribe dos restricciones que el diagrama no recoge (por ejemplo, sobre el stock)."],
   comp=["`LÍNEA_PEDIDO` es una entidad débil de `PEDIDO`.",
         "`teléfono` es multivaluado y `dirección` es compuesto.",
         "`importe_total` es un atributo derivado.",
         "La relación entre categorías es reflexiva con los roles *categoría* y *subcategoría*."],
   err=["Guardar `importe_total` como atributo normal: se desincroniza si cambia una línea.",
        "Obtener el precio de la línea siempre desde `PRODUCTO`: los pedidos antiguos cambiarían de importe cuando suba el precio."],
   amp="Un producto puede pertenecer a **varias categorías** a la vez. ¿Cambia la cardinalidad? ¿Qué tabla aparecerá al pasar al modelo relacional?",
   dec=["`LÍNEA_PEDIDO` depende de `PEDIDO`: su identificador es (número de pedido, número de línea).",
        "`precio_unitario` guarda el precio **histórico** de la venta. Es un dato distinto del precio actual del producto.",
        "*Subcategoría* es reflexiva 1:N: una categoría tiene como mucho una categoría padre y puede tener muchas hijas."],
   sup=["Un cliente puede registrarse sin haber hecho pedidos.",
        "Un pedido tiene al menos una línea: (1,N).",
        "Un producto pertenece a una sola categoría.",
        "La cantidad pedida no puede superar el stock (restricción textual)."],
   model=Model("Tienda online: pedidos, líneas y categorías",
               "CLIENTE realiza PEDIDO. PEDIDO incluye LÍNEA_PEDIDO (débil). LÍNEA_PEDIDO se refiere a PRODUCTO. PRODUCTO pertenece a CATEGORÍA, que puede ser subcategoría de otra.",
               [E("CLIENTE", [K("email"), A("nombre"), A("apellidos"), C("dirección", "calle", "cód_postal", "ciudad"), MV("teléfono")]),
                E("PEDIDO", [K("nº_pedido"), A("fecha"), A("estado"), D("importe_total")]),
                E("LÍNEA_PEDIDO", [KP("nº_línea"), A("cantidad"), A("precio_unitario")], weak=True),
                E("PRODUCTO", [K("código"), A("nombre"), A("descripción"), A("precio"), A("stock")]),
                E("CATEGORÍA", [K("cód_categoría"), A("nombre")])],
               [R("realiza", [("CLIENTE", "(1,1)", None), ("PEDIDO", "(0,N)", None)]),
                R("incluye", [("PEDIDO", "(1,1)", None), ("LÍNEA_PEDIDO", "(1,N)", None)], ident=True),
                R("se refiere a", [("LÍNEA_PEDIDO", "(0,N)", None), ("PRODUCTO", "(1,1)", None)]),
                R("pertenece a", [("PRODUCTO", "(0,N)", None), ("CATEGORÍA", "(1,1)", None)]),
                R("subcategoría", [("CATEGORÍA", "(0,1)", "padre"), ("CATEGORÍA", "(0,N)", "hija")])]))

ej(n=8, titulo="Concesionario: ventas, revisiones y mecánicos", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + supuestos",
   objetivo="Combinar una entidad débil con una relación reflexiva de supervisión y decidir cómo guardar los trabajos de una revisión.",
   contexto="Un concesionario gestiona la venta de coches y las revisiones de su taller.",
   enun=["De cada **coche** se conoce la matrícula, la marca, el modelo, el color y el precio de venta. De cada **cliente** se registra un código interno, el NIF, el nombre, la dirección, la ciudad y el teléfono. Un cliente puede comprar varios coches, pero cada coche lo compra un único cliente.",
         "En el taller se realizan **revisiones**. Cada revisión se identifica por un número secuencial dentro de cada coche (1, 2, 3…). De cada revisión se quiere saber si se ha cambiado el filtro, el aceite o los frenos, y si se ha hecho algún otro trabajo. Un coche puede pasar muchas revisiones.",
         "Cada revisión la realiza un único **mecánico**, del que se conoce el código de empleado, el DNI, el nombre, el teléfono y la dirección. Un mecánico realiza muchas revisiones. Entre los mecánicos hay un **supervisor** que coordina el trabajo de otros mecánicos."],
   tareas=["Dibuja el diagrama EER con la entidad débil y la relación reflexiva.",
           "Decide cómo guardar los trabajos de la revisión (booleanos o atributo multivaluado) y justifica la elección.",
           "El cliente tiene un **código interno** y un **NIF**. ¿Cuál eliges como identificador? ¿Qué papel tiene el otro?",
           "Anota los supuestos y una restricción textual."],
   comp=["`REVISIÓN` es débil de `COCHE` y su discriminador es el número de revisión.",
         "El supervisor se modela con una relación **reflexiva** sobre `MECÁNICO`.",
         "Has indicado qué clave es candidata y cuál es alternativa en `CLIENTE`.",
         "Un coche recién fabricado, no vendido aún, es posible en tu modelo."],
   err=["Crear una entidad `SUPERVISOR` aparte. Un supervisor es un mecánico.",
        "Dar al coche un identificador artificial y olvidar que la matrícula ya identifica."],
   amp="El taller quiere guardar **qué piezas** se cambiaron en cada revisión y cuántas. ¿Qué entidad y qué relación añades? ¿Qué atributo lleva la relación?",
   dec=["`REVISIÓN` es débil porque su número solo es único dentro de cada coche.",
        "Un mecánico tiene como mucho un supervisor, y un supervisor puede coordinar a muchos mecánicos: relación reflexiva 1:N con roles.",
        "En `CLIENTE`, el código interno es el identificador elegido; el NIF es una **clave alternativa**: único, pero no se usa para relacionar."],
   sup=["Un coche puede estar sin vender: (0,1) del lado del cliente.",
        "Una revisión siempre la hace un mecánico.",
        "Los trabajos de la revisión se guardan como cuatro atributos booleanos más un texto libre `otros`.",
        "Un mecánico no puede supervisarse a sí mismo (restricción textual)."],
   model=Model("Concesionario: ventas, revisiones y mecánicos",
               "CLIENTE compra COCHE (1:N). COCHE pasa REVISIÓN (identificadora, débil). MECÁNICO realiza REVISIÓN. MECÁNICO supervisa a MECÁNICO.",
               [E("CLIENTE", [K("cód_cliente"), A("nif"), A("nombre"), A("dirección"), A("ciudad"), A("teléfono")]),
                E("COCHE", [K("matrícula"), A("marca"), A("modelo"), A("color"), A("precio_venta")]),
                E("REVISIÓN", [KP("nº_revisión"), A("cambio_filtro"), A("cambio_aceite"), A("cambio_frenos"), A("otros")], weak=True),
                E("MECÁNICO", [K("cód_empleado"), A("dni"), A("nombre"), A("teléfono"), A("dirección")])],
               [R("compra", [("CLIENTE", "(0,1)", None), ("COCHE", "(0,N)", None)]),
                R("pasa", [("COCHE", "(1,1)", None), ("REVISIÓN", "(0,N)", None)], ident=True),
                R("realiza", [("MECÁNICO", "(1,1)", None), ("REVISIÓN", "(0,N)", None)]),
                R("supervisa", [("MECÁNICO", "(0,1)", "supervisor"), ("MECÁNICO", "(0,N)", "supervisado")])]))

ej(n=9, titulo="Consultora de software: proyectos, tareas y desarrolladores", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Modelar una jerarquía de dependencia (cliente → proyecto → tarea) con una N:M con atributos y una relación reflexiva.",
   contexto="Una consultora tecnológica quiere controlar sus proyectos y las horas de su equipo.",
   enun=["De los **clientes** se registra el CIF, la razón social, el sitio web y el teléfono. Un cliente puede encargar varios proyectos, pero cada proyecto pertenece a un único cliente.",
         "De cada **proyecto** se conoce el código, el nombre, la fecha de inicio y el presupuesto. Un proyecto se descompone en varias **tareas**, numeradas dentro del proyecto (1, 2, 3…). De cada tarea se guarda la descripción, las horas estimadas y su estado (*pendiente*, *en proceso* o *completada*).",
         "De los **desarrolladores** se guarda el número de empleado, el DNI, el nombre, la especialidad y el nivel. Un desarrollador se asigna a varias tareas y en una tarea trabajan varios desarrolladores, con las **horas reales** dedicadas. Algunos desarrolladores senior ejercen de **mentores** de desarrolladores junior."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "¿Por qué `TAREA` es una entidad débil y `PROYECTO` no? Escribe el identificador de cada una.",
           "Explica por qué `horas_reales` está en la relación y `horas_estimadas` en la entidad.",
           "Escribe dos restricciones: una sobre el estado de la tarea y otra sobre los mentores."],
   comp=["`TAREA` depende de `PROYECTO`; `PROYECTO` depende (solo por relación) de `CLIENTE`.",
         "*Trabaja en* tiene el atributo `horas_reales`.",
         "*Tutela* es reflexiva sobre `DESARROLLADOR`.",
         "El estado de la tarea tiene un dominio cerrado de tres valores y lo has anotado."],
   err=["Hacer `PROYECTO` débil de `CLIENTE`. El código del proyecto ya lo identifica.",
        "Poner `horas_reales` en `TAREA`: ¿de qué desarrollador serían?"],
   amp="Se quiere que cada desarrollador tenga **un único rol** por proyecto (jefe de proyecto, analista, programador…). ¿Dónde se guarda este dato? ¿Es un atributo de la relación o hay que añadir una entidad?",
   dec=["*Se descompone en* es identificadora: (código de proyecto, número de tarea).",
        "*Trabaja en* es N:M con `horas_reales`: el dato depende de la pareja desarrollador-tarea.",
        "*Tutela* es una reflexiva 1:N: un junior tiene como mucho un mentor; un mentor puede tutelar a varios."],
   sup=["Un proyecto tiene al menos una tarea: (1,N).",
        "Una tarea recién creada puede no tener desarrolladores asignados.",
        "Solo un desarrollador de nivel *senior* puede ser mentor (restricción textual).",
        "El estado de la tarea solo admite *pendiente*, *en proceso* o *completada* (restricción de dominio)."],
   model=Model("Consultora de software: proyectos, tareas y desarrolladores",
               "CLIENTE encarga PROYECTO (1:N). PROYECTO se descompone en TAREA (débil). DESARROLLADOR trabaja en TAREA (N:M con horas reales). DESARROLLADOR tutela a DESARROLLADOR.",
               [E("CLIENTE", [K("cif"), A("razón_social"), A("sitio_web"), A("teléfono")]),
                E("PROYECTO", [K("cód_proyecto"), A("nombre"), A("fecha_inicio"), A("presupuesto")]),
                E("TAREA", [KP("nº_tarea"), A("descripción"), A("horas_estimadas"), A("estado")], weak=True),
                E("DESARROLLADOR", [K("nº_empleado"), A("dni"), A("nombre"), A("especialidad"), A("nivel")])],
               [R("encarga", [("CLIENTE", "(1,1)", None), ("PROYECTO", "(0,N)", None)]),
                R("se descompone en", [("PROYECTO", "(1,1)", None), ("TAREA", "(1,N)", None)], ident=True),
                R("trabaja en", [("DESARROLLADOR", "(0,N)", None), ("TAREA", "(0,N)", None)], [A("horas_reales")]),
                R("tutela", [("DESARROLLADOR", "(0,1)", "mentor"), ("DESARROLLADOR", "(0,N)", "tutelado")])]))

ej(n=10, titulo="Cadena hotelera: hoteles, habitaciones y reservas", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Modelar un caso de reservas con entidad débil, N:M repetible entre las mismas entidades y supervisión reflexiva.",
   contexto="Una cadena hotelera estructura el sistema central de reservas de sus establecimientos.",
   enun=["De cada **hotel** se conoce el código, el nombre, la categoría (estrellas), la dirección y la ciudad.",
         "Un hotel dispone de varias **habitaciones**. Cada habitación se identifica por su número dentro del hotel (101, 102, 201…); se guarda el tipo (*individual*, *doble* o *suite*) y el precio por noche.",
         "De los **clientes** se registra el DNI, el nombre, el correo y el teléfono. Un cliente **reserva** habitaciones concretas para un periodo, con la fecha de entrada, la fecha de salida y el precio total de la estancia. Un cliente puede alojarse varias veces en la misma habitación.",
         "De los **empleados** se conoce el código, el nombre y el puesto. Cada empleado está asignado a un hotel. Las **gobernantas** de planta supervisan al personal de limpieza de su hotel."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Identifica por completo la entidad débil `HABITACIÓN` y razona por qué el número de habitación no basta.",
           "Un cliente reserva la misma habitación dos veces. ¿Qué atributo permite distinguir las reservas?",
           "Escribe tres restricciones que el diagrama no recoge (solapes de fechas, salida posterior a entrada, supervisión dentro del mismo hotel…)."],
   comp=["`HABITACIÓN` es débil de `HOTEL`.",
         "*Reserva* es una N:M entre `CLIENTE` y `HABITACIÓN` con `fecha_entrada` como discriminador.",
         "La supervisión es una relación reflexiva con roles.",
         "Has anotado la restricción sobre solapes de fechas."],
   err=["Relacionar `CLIENTE` con `HOTEL` y no con `HABITACIÓN`: no sabrías qué habitación se ha reservado.",
        "Usar el número de habitación como clave global: la 101 existe en todos los hoteles."],
   amp="Una reserva puede incluir **varias habitaciones** (una familia reserva dos). ¿Qué entidad intermedia se introduce y qué cambia en la relación con las habitaciones?",
   dec=["`HABITACIÓN` se identifica por (código de hotel, número de habitación).",
        "*Reserva* lleva `fecha_entrada` como discriminador: permite repetir cliente y habitación en estancias distintas.",
        "*Supervisa* es una reflexiva 1:N: una gobernanta supervisa a varios empleados de limpieza."],
   sup=["Un hotel tiene al menos una habitación: (1,N).",
        "Todo empleado está asignado a un único hotel.",
        "`precio_total` se guarda para conservar el precio pactado aunque cambie la tarifa.",
        "La fecha de salida es posterior a la de entrada y no hay dos reservas solapadas para la misma habitación (restricciones textuales)."],
   model=Model("Cadena hotelera: hoteles, habitaciones y reservas",
               "HOTEL dispone de HABITACIÓN (débil). CLIENTE reserva HABITACIÓN (N:M con fechas y precio). EMPLEADO trabaja en HOTEL. EMPLEADO supervisa a EMPLEADO.",
               [E("HOTEL", [K("cód_hotel"), A("nombre"), A("estrellas"), A("dirección"), A("ciudad")]),
                E("HABITACIÓN", [KP("nº_habitación"), A("tipo"), A("precio_noche")], weak=True),
                E("CLIENTE", [K("dni"), A("nombre"), A("email"), A("teléfono")]),
                E("EMPLEADO", [K("cód_empleado"), A("nombre"), A("puesto")])],
               [R("dispone de", [("HOTEL", "(1,1)", None), ("HABITACIÓN", "(1,N)", None)], ident=True),
                R("reserva", [("CLIENTE", "(0,N)", None), ("HABITACIÓN", "(0,N)", None)],
                  [KP("fecha_entrada"), A("fecha_salida"), A("precio_total")]),
                R("trabaja en", [("EMPLEADO", "(1,N)", None), ("HOTEL", "(1,1)", None)]),
                R("supervisa", [("EMPLEADO", "(0,1)", "gobernanta"), ("EMPLEADO", "(0,N)", "supervisado")])]))

ej(n=11, titulo="Universidad: facultades, departamentos y cátedras", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + restricciones",
   objetivo="Combinar una cadena de dependencias jerárquicas, una relación 1:1 con condiciones y una reflexiva.",
   contexto="Una universidad pública organiza su estructura académica e investigadora.",
   enun=["De las **facultades** se guarda el código y el nombre. Una facultad engloba varios **departamentos**, de los que se conoce el código y el área de conocimiento.",
         "Dentro de cada departamento se crean **cátedras** de investigación. Cada cátedra se identifica por un número interno dentro de su departamento y tiene un nombre y un presupuesto.",
         "De los **profesores** se guarda el número de registro, el DNI, el nombre, la categoría docente y la fecha de incorporación. Un profesor pertenece a un único departamento. Un profesor con categoría de *catedrático* puede ser nombrado **director** de una cátedra. Además, los profesores veteranos son **tutores** de los profesores noveles."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Identifica la entidad débil, su propietaria y el identificador completo.",
           "Calcula las cardinalidades de *dirige* y razona por qué una cátedra siempre tiene director pero un profesor puede no dirigir ninguna.",
           "Escribe las restricciones textuales: quién puede dirigir una cátedra y de qué departamento."],
   comp=["`CATEDRA` es débil de `DEPARTAMENTO`.",
         "*Dirige* es 1:1: la cátedra tiene (1,1) director y el profesor (0,1) cátedra.",
         "*Tutoriza* es reflexiva con roles *veterano* y *novel*.",
         "Has indicado que el director debe ser catedrático y del mismo departamento."],
   err=["Convertir `CATEDRÁTICO` en una entidad sin plantearte que es un profesor con una categoría concreta.",
        "No exigir que el director pertenezca al departamento de la cátedra."],
   amp="Los **catedráticos** tienen datos propios (año de oposición, sexenios). Convierte esta situación en una **especialización** de `PROFESOR` y razona qué restricción desaparece del texto.",
   dec=["Cadena 1:N: facultad → departamento → cátedra (la última, identificadora).",
        "*Dirige* es 1:1 con mínimo 1 en la cátedra y 0 en el profesor.",
        "*Tutoriza* es una reflexiva 1:N."],
   sup=["Todo profesor pertenece a un departamento: (1,1).",
        "Una cátedra siempre tiene director.",
        "Solo un catedrático puede dirigir una cátedra y debe ser del departamento de la cátedra (restricciones textuales).",
        "Un novel tiene como mucho un tutor."],
   model=Model("Universidad: facultades, departamentos y cátedras",
               "FACULTAD engloba DEPARTAMENTO. DEPARTAMENTO crea CÁTEDRA (débil). PROFESOR pertenece a DEPARTAMENTO, dirige CÁTEDRA y tutoriza a PROFESOR.",
               [E("FACULTAD", [K("cód_facultad"), A("nombre")]),
                E("DEPARTAMENTO", [K("cód_departamento"), A("área_conocimiento")]),
                E("CÁTEDRA", [KP("nº_cátedra"), A("nombre"), A("presupuesto")], weak=True),
                E("PROFESOR", [K("nº_registro"), A("dni"), A("nombre"), A("categoría"), A("fecha_incorporación")])],
               [R("engloba", [("FACULTAD", "(1,1)", None), ("DEPARTAMENTO", "(1,N)", None)]),
                R("crea", [("DEPARTAMENTO", "(1,1)", None), ("CÁTEDRA", "(0,N)", None)], ident=True),
                R("pertenece a", [("PROFESOR", "(1,N)", None), ("DEPARTAMENTO", "(1,1)", None)]),
                R("dirige", [("PROFESOR", "(1,1)", None), ("CÁTEDRA", "(0,1)", None)]),
                R("tutoriza", [("PROFESOR", "(0,1)", "veterano"), ("PROFESOR", "(0,N)", "novel")])]))

ej(n=12, titulo="Centro de menores: residentes, educadores e informes", nivel=2, dur="1 sesión",
   ra="RA6: a, d, e, h", entrega="Diagrama EER + nota de protección de datos",
   objetivo="Modelar una entidad débil con borrado en cascada y valorar la protección de datos de menores.",
   contexto="Un centro de acogida de menores necesita un registro informatizado de residentes y de sus expedientes.",
   enun=["De cada **menor residente** se conoce el número de expediente, el nombre, los apellidos, la fecha de nacimiento y los datos de contacto de sus tutores legales (nombre del padre, nombre de la madre y teléfono).",
         "De cada **educador** se registra el número de colegiado, el DNI, el nombre, los apellidos y la especialidad (*psicología*, *trabajo social* o *educación social*). Un educador tutela a varios menores, pero cada menor tiene un único educador tutor principal. Además, un **educador coordinador** supervisa al resto del equipo técnico.",
         "Para cada menor se abren **informes de seguimiento**. Cada informe se identifica con un número correlativo para ese menor (1, 2, 3…) y recoge la fecha, la valoración evolutiva y las incidencias. Si el expediente de un menor se cancela por cumplimiento de la medida, todos sus informes se eliminan."],
   tareas=["Dibuja el diagrama EER en notación de Chen.",
           "Explica qué significa «se eliminan todos sus informes» en el modelo y dónde se documenta.",
           "Clasifica `datos_tutores`: ¿atributo compuesto o entidad? Razona la decisión.",
           "Redacta una nota sobre qué datos serían **especialmente sensibles** y qué medidas pedirías (RGPD y LOPDGDD)."],
   comp=["`INFORME` es débil de `MENOR`.",
         "*Coordina* es reflexiva: un educador supervisa a varios.",
         "El educador tutor principal es obligatorio: (1,1) junto a `EDUCADOR`.",
         "La nota de protección de datos cita al menos el principio de minimización."],
   err=["Guardar la lista de informes como atributo multivaluado de `MENOR`: cada informe tiene atributos propios.",
        "Perder de vista que borrar un menor borra sus informes. Es una regla de integridad, no un detalle de implementación."],
   amp="Un menor puede ser **trasladado** a otro centro y volver años después. ¿Cómo cambiaría el identificador del menor y qué entidad nueva harías aparecer para conservar el historial?",
   dec=["`INFORME` depende de `MENOR`: (nº expediente, nº informe).",
        "El borrado en cascada se documenta como restricción: el diagrama solo muestra la dependencia.",
        "`datos_tutores` es un atributo compuesto porque no se consulta de forma independiente."],
   sup=["Todo menor tiene un educador tutor: (1,1).",
        "El coordinador no tiene supervisor; el resto tiene uno como máximo.",
        "Los informes de menores se cancelan en cascada al cerrar el expediente (restricción de borrado).",
        "Los datos de menores requieren medidas reforzadas de acceso y confidencialidad."],
   model=Model("Centro de menores: residentes, educadores e informes",
               "EDUCADOR tutela a MENOR (1:N). EDUCADOR coordina a EDUCADOR. MENOR tiene INFORME (débil).",
               [E("MENOR", [K("nº_expediente"), A("nombre"), A("apellidos"), A("fecha_nacimiento"),
                            C("datos_tutores", "nombre_padre", "nombre_madre", "teléfono")]),
                E("EDUCADOR", [K("nº_colegiado"), A("dni"), A("nombre"), A("apellidos"), A("especialidad")]),
                E("INFORME", [KP("nº_informe"), A("fecha"), A("valoración"), A("incidencias")], weak=True)],
               [R("tutela", [("EDUCADOR", "(1,1)", None), ("MENOR", "(0,N)", None)]),
                R("coordina", [("EDUCADOR", "(0,1)", "coordinador"), ("EDUCADOR", "(0,N)", "coordinado")]),
                R("tiene", [("MENOR", "(1,1)", None), ("INFORME", "(0,N)", None)], ident=True)]))
